"""Canonical import/publish governance states, checks, and fingerprints.

IMPORT_READY, MODEL_READY, and PUBLISH_READY are distinct. Only deterministic
evaluators may emit IMPORT_READY and PUBLISH_READY. MODEL_READY remains owned
by the existing execution pipeline.
"""

from __future__ import annotations

from enum import StrEnum


class ImportReadinessStatus(StrEnum):
    IMPORT_READY = "IMPORT_READY"
    NOT_IMPORT_READY = "NOT_IMPORT_READY"


class PublishReadinessStatus(StrEnum):
    PUBLISH_READY = "PUBLISH_READY"
    NOT_PUBLISH_READY = "NOT_PUBLISH_READY"


class SourceType(StrEnum):
    GCS_UPLOAD = "GCS_UPLOAD"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    BIGQUERY = "BIGQUERY"


class GoogleCapability(StrEnum):
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    BIGQUERY_READ = "BIGQUERY_READ"
    BIGQUERY_WRITE = "BIGQUERY_WRITE"


class ConnectionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REAUTH_REQUIRED = "REAUTH_REQUIRED"
    REVOKED = "REVOKED"


class BindingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


class BigQueryObjectType(StrEnum):
    TABLE = "TABLE"
    VIEW = "VIEW"
    MATERIALIZED_VIEW = "MATERIALIZED_VIEW"
    EXTERNAL = "EXTERNAL"
    UNKNOWN = "UNKNOWN"


class CheckSeverity(StrEnum):
    PASS = "PASS"
    ATTENTION = "ATTENTION"
    ERROR = "ERROR"


class GovernanceCheckCode(StrEnum):
    CONNECTION_ACTIVE = "CONNECTION_ACTIVE"
    SOURCE_AUTHORIZED = "SOURCE_AUTHORIZED"
    SOURCE_BOUND = "SOURCE_BOUND"
    RESOURCE_EXISTS = "RESOURCE_EXISTS"
    FORMAT_SUPPORTED = "FORMAT_SUPPORTED"
    OBJECT_NONEMPTY = "OBJECT_NONEMPTY"
    SCHEMA_INSPECTABLE = "SCHEMA_INSPECTABLE"
    VERSION_IDENTITY_AVAILABLE = "VERSION_IDENTITY_AVAILABLE"
    PROVIDER_RESOLVED = "PROVIDER_RESOLVED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_MAPPING_UNAMBIGUOUS = "ROLE_MAPPING_UNAMBIGUOUS"
    DUPLICATE_SELECTION_ABSENT = "DUPLICATE_SELECTION_ABSENT"
    MANIFEST_COMPLETE = "MANIFEST_COMPLETE"
    CONNECTION_INACTIVE = "CONNECTION_INACTIVE"
    BINDING_MISSING = "BINDING_MISSING"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"
    OBJECT_EMPTY = "OBJECT_EMPTY"
    SCHEMA_UNREADABLE = "SCHEMA_UNREADABLE"
    SOURCE_ROLE_MISSING = "SOURCE_ROLE_MISSING"
    SOURCE_ROLE_AMBIGUOUS = "SOURCE_ROLE_AMBIGUOUS"
    PROVIDER_UNRESOLVED = "PROVIDER_UNRESOLVED"
    SOURCE_VERSION_UNVERIFIABLE = "SOURCE_VERSION_UNVERIFIABLE"
    SOURCE_CHANGED_SINCE_IMPORT_READY = "SOURCE_CHANGED_SINCE_IMPORT_READY"
    DESTINATION_NOT_WRITABLE = "DESTINATION_NOT_WRITABLE"
    DESTINATION_LOCATION_MISMATCH = "DESTINATION_LOCATION_MISMATCH"
    MODEL_READY_REQUIRED = "MODEL_READY_REQUIRED"
    PUBLISH_ARTIFACT_MISSING = "PUBLISH_ARTIFACT_MISSING"
    MODEL_READY_VERIFIED = "MODEL_READY_VERIFIED"
    DESTINATION_BOUND = "DESTINATION_BOUND"
    DESTINATION_AUTHORIZED = "DESTINATION_AUTHORIZED"
    DESTINATION_EXISTS_OR_CREATABLE = "DESTINATION_EXISTS_OR_CREATABLE"
    DESTINATION_WRITABLE = "DESTINATION_WRITABLE"
    LOCATION_COMPATIBLE = "LOCATION_COMPATIBLE"
    NAMING_DETERMINISTIC = "NAMING_DETERMINISTIC"
    REQUIRED_ARTIFACTS_PRESENT = "REQUIRED_ARTIFACTS_PRESENT"
    OVERWRITE_POLICY_EXPLICIT = "OVERWRITE_POLICY_EXPLICIT"
    LINEAGE_COMPLETE = "LINEAGE_COMPLETE"
    IMPORT_NOT_READY = "IMPORT_NOT_READY"
    IMPORT_RECEIPT_SUPERSEDED = "IMPORT_RECEIPT_SUPERSEDED"
    FOUNDATION_SOURCE_NOT_READY = "FOUNDATION_SOURCE_NOT_READY"
    FOUNDATION_LINEAGE_MISMATCH = "FOUNDATION_LINEAGE_MISMATCH"
    MATERIALIZATION_LIMIT_EXCEEDED = "MATERIALIZATION_LIMIT_EXCEEDED"
    SOURCE_MATERIALIZATION_FAILED = "SOURCE_MATERIALIZATION_FAILED"
    SOURCE_COPY_INCOMPLETE = "SOURCE_COPY_INCOMPLETE"
    UPLOAD_VERIFICATION_FAILED = "UPLOAD_VERIFICATION_FAILED"
    GOOGLE_REAUTH_REQUIRED = "GOOGLE_REAUTH_REQUIRED"
    PUBLISH_NOT_READY = "PUBLISH_NOT_READY"
    PUBLISH_VERIFICATION_FAILED = "PUBLISH_VERIFICATION_FAILED"
    PUBLISH_TARGET_CONFLICT = "PUBLISH_TARGET_CONFLICT"
    PARTIAL_PUBLISH = "PARTIAL_PUBLISH"


DRIVE_DEPOT_NAME = "prem3-modeling"
BIGQUERY_DEPOT_DATASET_ID = "prem3_modeling"
BIGQUERY_DEPOT_FRIENDLY_NAME = "prem3-modeling"

DRIVE_SCOPE = "https://www.googleapis.com/auth/drive.file"
BIGQUERY_READ_SCOPE = "https://www.googleapis.com/auth/bigquery.readonly"
BIGQUERY_WRITE_SCOPE = "https://www.googleapis.com/auth/bigquery"
OPENID_SCOPES: tuple[str, ...] = (
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
)

CAPABILITY_SCOPES: dict[GoogleCapability, tuple[str, ...]] = {
    GoogleCapability.GOOGLE_DRIVE: (DRIVE_SCOPE,),
    GoogleCapability.BIGQUERY_READ: (BIGQUERY_READ_SCOPE,),
    GoogleCapability.BIGQUERY_WRITE: (BIGQUERY_WRITE_SCOPE,),
}

SUPPORTED_IMPORT_FORMATS: frozenset[str] = frozenset({"csv", "parquet", "json"})
SUPPORTED_BQ_IMPORT_TYPES: frozenset[BigQueryObjectType] = frozenset(
    {BigQueryObjectType.TABLE, BigQueryObjectType.VIEW}
)

PUBLISH_DRIVE_ARTIFACTS: tuple[str, ...] = (
    "model_ready.parquet",
    "model_ready.csv",
    "readiness_receipt.json",
    "meridian_input_contract.json",
    "meridian_eda_report.html",
    "prem3_run_manifest.json",
)

IMPORT_CONTRACT_VERSION = "prem3.import.v1"
PUBLISH_CONTRACT_VERSION = "prem3.publish.v1"
