"""Project Home availability and next-action vocabulary.

These are presentation/availability states. They do not replace
BUSINESS_CONTEXT_READY, FOUNDATION_SOURCE_READY, DATA_FOUNDATION_READY,
IMPORT_READY, MODEL_READY, or PUBLISH_READY.
"""

from __future__ import annotations

from enum import StrEnum


class CapabilityFamily(StrEnum):
    FOUNDATION = "FOUNDATION"
    BUSINESS_IQ = "BUSINESS_IQ"
    DATA_FOUNDATION = "DATA_FOUNDATION"
    MMM = "MMM"
    MTA = "MTA"
    FORECASTING = "FORECASTING"
    SCENARIO_SIMULATION = "SCENARIO_SIMULATION"
    BUDGET_OPTIMIZATION = "BUDGET_OPTIMIZATION"
    DECISION_INTELLIGENCE = "DECISION_INTELLIGENCE"
    PORTFOLIO_VIEW = "PORTFOLIO_VIEW"
    TEAM_SEATS = "TEAM_SEATS"
    API_ACCESS = "API_ACCESS"


class CapabilityAvailability(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    AVAILABLE_TO_CONFIGURE = "AVAILABLE_TO_CONFIGURE"
    IN_PROGRESS = "IN_PROGRESS"
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    UNAVAILABLE_ENTITLEMENT = "UNAVAILABLE_ENTITLEMENT"
    NEEDS_FOUNDATION = "NEEDS_FOUNDATION"
    NEEDS_SOURCE = "NEEDS_SOURCE"
    NEEDS_ACCEPTED_MODEL = "NEEDS_ACCEPTED_MODEL"


class NextActionType(StrEnum):
    START_BUSINESS_IQ = "START_BUSINESS_IQ"
    CONTINUE_BUSINESS_IQ = "CONTINUE_BUSINESS_IQ"
    OPEN_BUSINESS_IQ = "OPEN_BUSINESS_IQ"
    START_DATA_FOUNDATION = "START_DATA_FOUNDATION"
    CONTINUE_DATA_FOUNDATION = "CONTINUE_DATA_FOUNDATION"
    OPEN_DATA_FOUNDATION = "OPEN_DATA_FOUNDATION"
    CONTINUE_MMM = "CONTINUE_MMM"
    REVIEW_MMM = "REVIEW_MMM"
    SETUP_MTA = "SETUP_MTA"
    SELECT_MTA_KEY_EVENT = "SELECT_MTA_KEY_EVENT"
    OPEN_MTA = "OPEN_MTA"
    SETUP_FORECAST = "SETUP_FORECAST"
    VIEW_SCENARIO_REQUIREMENTS = "VIEW_SCENARIO_REQUIREMENTS"
    VIEW_OPTIMIZATION_REQUIREMENTS = "VIEW_OPTIMIZATION_REQUIREMENTS"
    REVIEW_SOURCE = "REVIEW_SOURCE"
    REAUTHORIZE_SOURCE = "REAUTHORIZE_SOURCE"
    OPEN_INSIGHT = "OPEN_INSIGHT"
    REVIEW_DECISION = "REVIEW_DECISION"
    RETURN_PROJECT_HOME = "RETURN_PROJECT_HOME"


class AttentionSeverity(StrEnum):
    INFO = "INFO"
    REVIEW = "REVIEW"
    BLOCKER = "BLOCKER"


class AttentionState(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"


DEFAULT_MMM_ENGINE = "Google Meridian"
CANONICAL_BQ_DATASET = "prem3_modeling"
