"""Investment planning vocabulary. No readiness authority lives here."""

from __future__ import annotations

from enum import StrEnum


class SensitiveDataClass(StrEnum):
    CONTROL_PLANE_METADATA = "CONTROL_PLANE_METADATA"
    CUSTOMER_AMOUNT_TRANSIENT = "CUSTOMER_AMOUNT_TRANSIENT"


class InvestmentPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    SOURCE_STALE = "SOURCE_STALE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class BudgetScope(StrEnum):
    PAID_MEDIA_ONLY = "PAID_MEDIA_ONLY"
    PAID_MEDIA_PLUS_CREATIVE = "PAID_MEDIA_PLUS_CREATIVE"
    FULLY_LOADED_MARKETING_INVESTMENT = "FULLY_LOADED_MARKETING_INVESTMENT"
    CUSTOM = "CUSTOM"


class BudgetSourceGrain(StrEnum):
    MARKET_CHANNEL_QUARTER = "MARKET_CHANNEL_QUARTER"
    INITIATIVE_DETAIL = "INITIATIVE_DETAIL"
    MIXED = "MIXED"


class AmountKind(StrEnum):
    PLANNED = "PLANNED"
    APPROVED = "APPROVED"
    COMMITTED = "COMMITTED"
    FLEXIBLE = "FLEXIBLE"
    ACTUAL = "ACTUAL"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    REMAINING = "REMAINING"
    RECOMMENDED = "RECOMMENDED"


class PortfolioBaselineKind(StrEnum):
    APPROVED_PLAN = "APPROVED_PLAN"
    ACTUAL_YTD = "ACTUAL_YTD"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    TRANSIENT_SCENARIO = "TRANSIENT_SCENARIO"
    GOVERNED_ACTUALS = "GOVERNED_ACTUALS"


class MappingMethod(StrEnum):
    CHANNEL_REGISTRY = "CHANNEL_REGISTRY"
    BUSINESS_PROFILE_REGISTRY_REF = "BUSINESS_PROFILE_REGISTRY_REF"
    EXPLICIT_USER_MAP = "EXPLICIT_USER_MAP"


class PlanningErrorCode(StrEnum):
    UNRESOLVED_MARKET_IDENTITY = "UNRESOLVED_MARKET_IDENTITY"
    UNRESOLVED_CHANNEL_IDENTITY = "UNRESOLVED_CHANNEL_IDENTITY"
    LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY = "LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY"
    PLANNING_PERSISTENCE_BARRIER = "PLANNING_PERSISTENCE_BARRIER"
    PLANNING_AUTHORITY_DENIED = "PLANNING_AUTHORITY_DENIED"
    MISSING_NOT_ZERO = "MISSING_NOT_ZERO"
    ACTUALS_NOT_APPROVED_BUDGET = "ACTUALS_NOT_APPROVED_BUDGET"


class InvestmentPlanReadyStatus(StrEnum):
    NOT_SET = "NOT_SET"
    PENDING = "PENDING"
    INVESTMENT_PLAN_READY = "INVESTMENT_PLAN_READY"
    SOURCE_STALE = "SOURCE_STALE"


class EvidenceCoverageLabel(StrEnum):
    MMM = "MMM"
    MTA = "MTA"
    EXPERIMENT = "EXPERIMENT"
    BRAND = "BRAND"
    EXPOSURE_INTEGRITY = "EXPOSURE_INTEGRITY"
    NONE = "NONE"


class ExposureGuardrailRole(StrEnum):
    MODEL_INPUT = "MODEL_INPUT"
    CONSTRAINT = "CONSTRAINT"
    SCENARIO_GUARDRAIL = "SCENARIO_GUARDRAIL"
    APPROVAL_GUARDRAIL = "APPROVAL_GUARDRAIL"


class DriveBudgetFolderKind(StrEnum):
    BUDGETS = "BUDGETS"
    TEMPLATES = "TEMPLATES"
    PLANS = "PLANS"
    SCENARIOS = "SCENARIOS"
    PROPOSALS = "PROPOSALS"
