"""Investment planning vocabulary. No readiness authority lives here."""

from __future__ import annotations

from enum import StrEnum


class SensitiveDataClass(StrEnum):
    CONTROL_PLANE_METADATA = "CONTROL_PLANE_METADATA"
    CUSTOMER_AMOUNT_TRANSIENT = "CUSTOMER_AMOUNT_TRANSIENT"


class InvestmentPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    SOURCE_STALE = "SOURCE_STALE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class BudgetScope(StrEnum):
    PAID_MEDIA_ONLY = "PAID_MEDIA_ONLY"
    PAID_MEDIA_PLUS_CREATIVE = "PAID_MEDIA_PLUS_CREATIVE"
    FULLY_LOADED_MARKETING_INVESTMENT = "FULLY_LOADED_MARKETING_INVESTMENT"
    CUSTOM = "CUSTOM"


class BudgetSourceGrain(StrEnum):
    MARKET_CHANNEL_QUARTER = "MARKET_CHANNEL_QUARTER"
    INITIATIVE_DETAIL = "INITIATIVE_DETAIL"
    MIXED = "MIXED"


class AmountKind(StrEnum):
    PLANNED = "PLANNED"
    APPROVED = "APPROVED"
    COMMITTED = "COMMITTED"
    FLEXIBLE = "FLEXIBLE"
    ACTUAL = "ACTUAL"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    REMAINING = "REMAINING"
    RECOMMENDED = "RECOMMENDED"


class PortfolioBaselineKind(StrEnum):
    APPROVED_PLAN = "APPROVED_PLAN"
    ACTUAL_YTD = "ACTUAL_YTD"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    TRANSIENT_SCENARIO = "TRANSIENT_SCENARIO"
    GOVERNED_ACTUALS = "GOVERNED_ACTUALS"


class PortfolioCoverageState(StrEnum):
    PLAN_AND_ACTUALS = "PLAN_AND_ACTUALS"
    PLAN_ONLY = "PLAN_ONLY"
    ACTUALS_ONLY = "ACTUALS_ONLY"
    NEITHER = "NEITHER"


class MappingMethod(StrEnum):
    CHANNEL_REGISTRY = "CHANNEL_REGISTRY"
    BUSINESS_PROFILE_REGISTRY_REF = "BUSINESS_PROFILE_REGISTRY_REF"
    EXPLICIT_USER_MAP = "EXPLICIT_USER_MAP"


class PlanningErrorCode(StrEnum):
    UNRESOLVED_MARKET_IDENTITY = "UNRESOLVED_MARKET_IDENTITY"
    CANONICAL_MARKET_CONTRACT_PENDING = "CANONICAL_MARKET_CONTRACT_PENDING"
    UNRESOLVED_CHANNEL_IDENTITY = "UNRESOLVED_CHANNEL_IDENTITY"
    LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY = "LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY"
    PLANNING_PERSISTENCE_BARRIER = "PLANNING_PERSISTENCE_BARRIER"
    PLANNING_AUTHORITY_DENIED = "PLANNING_AUTHORITY_DENIED"
    MISSING_NOT_ZERO = "MISSING_NOT_ZERO"
    ACTUALS_NOT_APPROVED_BUDGET = "ACTUALS_NOT_APPROVED_BUDGET"
    SOURCE_CHANGED_SINCE_LOAD = "SOURCE_CHANGED_SINCE_LOAD"
    SOURCE_VERSION_UNVERIFIABLE = "SOURCE_VERSION_UNVERIFIABLE"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"
    BUDGET_FOLDER_DEGRADED = "BUDGET_FOLDER_DEGRADED"
    MIXED_GRAIN_UNRESOLVED = "MIXED_GRAIN_UNRESOLVED"
    ACTUALS_SOURCE_NOT_CONFIGURED = "ACTUALS_SOURCE_NOT_CONFIGURED"
    ACTUALS_SOURCE_UNAVAILABLE = "ACTUALS_SOURCE_UNAVAILABLE"
    ACTUALS_SOURCE_STALE = "ACTUALS_SOURCE_STALE"
    ACTUALS_SCHEMA_INVALID = "ACTUALS_SCHEMA_INVALID"
    PERIOD_MAPPING_REQUIRED = "PERIOD_MAPPING_REQUIRED"
    CURRENCY_REVIEW_REQUIRED = "CURRENCY_REVIEW_REQUIRED"
    PRODUCTION_ACTUALS_SOURCE_NOT_READY = "PRODUCTION_ACTUALS_SOURCE_NOT_READY"
    BQ_AUTHORIZATION_FAILED = "BQ_AUTHORIZATION_FAILED"
    BQ_SOURCE_NOT_FOUND = "BQ_SOURCE_NOT_FOUND"
    BQ_LOCATION_MISMATCH = "BQ_LOCATION_MISMATCH"
    BQ_QUERY_FAILED = "BQ_QUERY_FAILED"
    ACTUALS_MARKET_MAPPING_REQUIRED = "ACTUALS_MARKET_MAPPING_REQUIRED"
    ACTUALS_CHANNEL_MAPPING_REQUIRED = "ACTUALS_CHANNEL_MAPPING_REQUIRED"
    ACTUALS_DUPLICATE_GRAIN = "ACTUALS_DUPLICATE_GRAIN"
    SOURCE_AUTHORITY_INVALID = "SOURCE_AUTHORITY_INVALID"
    EVIDENCE_COVERAGE_REVIEW_REQUIRED = "EVIDENCE_COVERAGE_REVIEW_REQUIRED"
    EXPOSURE_SOURCE_NOT_READY = "EXPOSURE_SOURCE_NOT_READY"
    EXPOSURE_METRIC_NOT_COMPARABLE = "EXPOSURE_METRIC_NOT_COMPARABLE"
    EXPOSURE_DATA_STALE = "EXPOSURE_DATA_STALE"
    EXPOSURE_COVERAGE_INSUFFICIENT = "EXPOSURE_COVERAGE_INSUFFICIENT"
    EXPOSURE_ENTITY_MAPPING_REQUIRED = "EXPOSURE_ENTITY_MAPPING_REQUIRED"
    EXPOSURE_MODEL_INPUT_UNSUPPORTED = "EXPOSURE_MODEL_INPUT_UNSUPPORTED"
    EXPOSURE_HARD_CONSTRAINT_UNSUPPORTED = "EXPOSURE_HARD_CONSTRAINT_UNSUPPORTED"
    SPEND_QUALITY_RELATIONSHIP_REQUIRED = "SPEND_QUALITY_RELATIONSHIP_REQUIRED"
    EXPOSURE_GUARDRAIL_REVIEW_REQUIRED = "EXPOSURE_GUARDRAIL_REVIEW_REQUIRED"


class BudgetValidationCode(StrEnum):
    DRIVE_BINDING_ACTIVE = "DRIVE_BINDING_ACTIVE"
    BUDGET_FOLDER_BOUND = "BUDGET_FOLDER_BOUND"
    SOURCE_EXISTS = "SOURCE_EXISTS"
    SOURCE_VERSION_IDENTIFIED = "SOURCE_VERSION_IDENTIFIED"
    FORMAT_SUPPORTED = "FORMAT_SUPPORTED"
    SCHEMA_MAPPED = "SCHEMA_MAPPED"
    BUSINESS_PROFILE_PINNED = "BUSINESS_PROFILE_PINNED"
    MARKETS_RESOLVED = "MARKETS_RESOLVED"
    CHANNELS_RESOLVED = "CHANNELS_RESOLVED"
    QUARTERS_VALID = "QUARTERS_VALID"
    AMOUNTS_NONNEGATIVE = "AMOUNTS_NONNEGATIVE"
    BLANKS_ACKNOWLEDGED = "BLANKS_ACKNOWLEDGED"
    DUPLICATES_RESOLVED = "DUPLICATES_RESOLVED"
    MIXED_GRAIN_RESOLVED = "MIXED_GRAIN_RESOLVED"
    CURRENCY_SINGLE = "CURRENCY_SINGLE"
    DECLARED_TOTAL_RECONCILED = "DECLARED_TOTAL_RECONCILED"
    SOURCE_UNCHANGED = "SOURCE_UNCHANGED"
    CANONICAL_MARKET_CONTRACT = "CANONICAL_MARKET_CONTRACT"


class RowBudgetStatus(StrEnum):
    PLANNED = "PLANNED"
    COMMITTED = "COMMITTED"
    FLEXIBLE = "FLEXIBLE"


class InvestmentPlanReadyStatus(StrEnum):
    NOT_SET = "NOT_SET"
    PENDING = "PENDING"
    INVESTMENT_PLAN_READY = "INVESTMENT_PLAN_READY"
    SOURCE_STALE = "SOURCE_STALE"


class EvidenceCoverageLabel(StrEnum):
    DATA_FOUNDATION = "DATA_FOUNDATION"
    MMM = "MMM"
    MTA = "MTA"
    EXPERIMENT = "EXPERIMENT"
    BRAND = "BRAND"
    EXPOSURE_INTEGRITY = "EXPOSURE_INTEGRITY"
    NONE = "NONE"


class EvidenceCoverageScope(StrEnum):
    PROJECT = "PROJECT"
    MARKET = "MARKET"
    CHANNEL = "CHANNEL"
    MARKET_CHANNEL_PERIOD = "MARKET_CHANNEL_PERIOD"


class EvidenceCoverageStatus(StrEnum):
    COVERED = "COVERED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class ActualSpendSourceKind(StrEnum):
    SYNTHETIC = "SYNTHETIC"
    DATA_FOUNDATION = "DATA_FOUNDATION"


class ActualSpendAuthority(StrEnum):
    TEST_ONLY = "TEST_ONLY"
    DATA_FOUNDATION_VERIFIED = "DATA_FOUNDATION_VERIFIED"
    CUSTOMER_GOVERNED_SOURCE = "CUSTOMER_GOVERNED_SOURCE"
    SYSTEM_VERIFIED = "SYSTEM_VERIFIED"


class ActualSpendSourceStatus(StrEnum):
    CONFIGURED = "CONFIGURED"
    UNAVAILABLE = "UNAVAILABLE"
    STALE = "STALE"
    FRESH = "FRESH"
    UNKNOWN = "UNKNOWN"


class ActualsFreshnessState(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class PortfolioObservationType(StrEnum):
    ACTUAL_EXCEEDS_PLAN = "ACTUAL_EXCEEDS_PLAN"
    ACTUAL_BELOW_PLAN = "ACTUAL_BELOW_PLAN"
    ACTUAL_WITHOUT_PLAN = "ACTUAL_WITHOUT_PLAN"
    PLAN_WITHOUT_ACTUALS = "PLAN_WITHOUT_ACTUALS"
    MISSING_ACTUALS_SOURCE = "MISSING_ACTUALS_SOURCE"
    STALE_ACTUALS_SOURCE = "STALE_ACTUALS_SOURCE"
    UNRESOLVED_MARKET = "UNRESOLVED_MARKET"
    UNRESOLVED_CHANNEL = "UNRESOLVED_CHANNEL"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    PERIOD_MAPPING_REQUIRED = "PERIOD_MAPPING_REQUIRED"
    MEASUREMENT_COVERAGE_MISSING = "MEASUREMENT_COVERAGE_MISSING"
    MEASUREMENT_COVERAGE_PARTIAL = "MEASUREMENT_COVERAGE_PARTIAL"


class ObservationSeverity(StrEnum):
    INFO = "INFO"
    REVIEW = "REVIEW"
    WARNING = "WARNING"
    ERROR = "ERROR"


class ExposureGuardrailRole(StrEnum):
    MODEL_INPUT = "MODEL_INPUT"
    CONSTRAINT = "CONSTRAINT"
    SCENARIO_GUARDRAIL = "SCENARIO_GUARDRAIL"
    APPROVAL_GUARDRAIL = "APPROVAL_GUARDRAIL"


class ExposureOptimizationRole(StrEnum):
    MODEL_INPUT = "MODEL_INPUT"
    CONSTRAINT_OR_FEASIBILITY = "CONSTRAINT_OR_FEASIBILITY"
    SCENARIO_OR_REVIEW_GUARDRAIL = "SCENARIO_OR_REVIEW_GUARDRAIL"


class ExposureFreshnessState(StrEnum):
    UNKNOWN = "UNKNOWN"
    FRESH = "FRESH"
    STALE = "STALE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ExposureQualityStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    PASS = "PASS"
    REVIEW = "REVIEW"
    BLOCKER = "BLOCKER"


class DeliveryHealthFlag(StrEnum):
    LOW_VIEWABILITY = "LOW_VIEWABILITY"
    HIGH_IVT = "HIGH_IVT"
    LOW_IN_TARGET_RATE = "LOW_IN_TARGET_RATE"
    LOW_UNIQUE_REACH = "LOW_UNIQUE_REACH"
    OVER_FREQUENCY = "OVER_FREQUENCY"
    UNDER_FREQUENCY = "UNDER_FREQUENCY"
    HIGH_DELIVERY_CONCENTRATION = "HIGH_DELIVERY_CONCENTRATION"
    EXPOSURE_DATA_STALE = "EXPOSURE_DATA_STALE"
    EXPOSURE_DATA_INCOMPLETE = "EXPOSURE_DATA_INCOMPLETE"
    METRIC_COMPARABILITY_REVIEW = "METRIC_COMPARABILITY_REVIEW"
    HIGH_SPEND_LOW_QUALITY = "HIGH_SPEND_LOW_QUALITY"


class ExposureCoverageDimension(StrEnum):
    PORTFOLIO_SPEND = "PORTFOLIO_SPEND"
    CHANNEL = "CHANNEL"
    MARKET = "MARKET"
    CAMPAIGN_PROVIDER = "CAMPAIGN_PROVIDER"
    FRESHNESS = "FRESHNESS"


class DriveBudgetFolderKind(StrEnum):
    BUDGETS = "BUDGETS"
    TEMPLATES = "TEMPLATES"
    PLANS = "PLANS"
    SCENARIOS = "SCENARIOS"
    PROPOSALS = "PROPOSALS"
