"""Investment planning vocabulary. No readiness authority lives here."""

from __future__ import annotations

from enum import StrEnum


class SensitiveDataClass(StrEnum):
    CONTROL_PLANE_METADATA = "CONTROL_PLANE_METADATA"
    CUSTOMER_AMOUNT_TRANSIENT = "CUSTOMER_AMOUNT_TRANSIENT"


class InvestmentPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    SOURCE_STALE = "SOURCE_STALE"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class BudgetScope(StrEnum):
    PAID_MEDIA_ONLY = "PAID_MEDIA_ONLY"
    PAID_MEDIA_PLUS_CREATIVE = "PAID_MEDIA_PLUS_CREATIVE"
    FULLY_LOADED_MARKETING_INVESTMENT = "FULLY_LOADED_MARKETING_INVESTMENT"
    CUSTOM = "CUSTOM"


class BudgetSourceGrain(StrEnum):
    MARKET_CHANNEL_QUARTER = "MARKET_CHANNEL_QUARTER"
    INITIATIVE_DETAIL = "INITIATIVE_DETAIL"
    MIXED = "MIXED"


class AmountKind(StrEnum):
    PLANNED = "PLANNED"
    APPROVED = "APPROVED"
    COMMITTED = "COMMITTED"
    FLEXIBLE = "FLEXIBLE"
    ACTUAL = "ACTUAL"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    REMAINING = "REMAINING"
    RECOMMENDED = "RECOMMENDED"


class PortfolioBaselineKind(StrEnum):
    APPROVED_PLAN = "APPROVED_PLAN"
    ACTUAL_YTD = "ACTUAL_YTD"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    TRANSIENT_SCENARIO = "TRANSIENT_SCENARIO"
    GOVERNED_ACTUALS = "GOVERNED_ACTUALS"


class PortfolioCoverageState(StrEnum):
    PLAN_AND_ACTUALS = "PLAN_AND_ACTUALS"
    PLAN_ONLY = "PLAN_ONLY"
    ACTUALS_ONLY = "ACTUALS_ONLY"
    NEITHER = "NEITHER"


class MappingMethod(StrEnum):
    CHANNEL_REGISTRY = "CHANNEL_REGISTRY"
    BUSINESS_PROFILE_REGISTRY_REF = "BUSINESS_PROFILE_REGISTRY_REF"
    EXPLICIT_USER_MAP = "EXPLICIT_USER_MAP"


class PlanningErrorCode(StrEnum):
    UNRESOLVED_MARKET_IDENTITY = "UNRESOLVED_MARKET_IDENTITY"
    CANONICAL_MARKET_CONTRACT_PENDING = "CANONICAL_MARKET_CONTRACT_PENDING"
    UNRESOLVED_CHANNEL_IDENTITY = "UNRESOLVED_CHANNEL_IDENTITY"
    LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY = "LEGACY_ALLOCATION_NOT_VALUE_AUTHORITY"
    PLANNING_PERSISTENCE_BARRIER = "PLANNING_PERSISTENCE_BARRIER"
    PLANNING_AUTHORITY_DENIED = "PLANNING_AUTHORITY_DENIED"
    MISSING_NOT_ZERO = "MISSING_NOT_ZERO"
    ACTUALS_NOT_APPROVED_BUDGET = "ACTUALS_NOT_APPROVED_BUDGET"
    SOURCE_CHANGED_SINCE_LOAD = "SOURCE_CHANGED_SINCE_LOAD"
    SOURCE_VERSION_UNVERIFIABLE = "SOURCE_VERSION_UNVERIFIABLE"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"
    BUDGET_FOLDER_DEGRADED = "BUDGET_FOLDER_DEGRADED"
    MIXED_GRAIN_UNRESOLVED = "MIXED_GRAIN_UNRESOLVED"


class BudgetValidationCode(StrEnum):
    DRIVE_BINDING_ACTIVE = "DRIVE_BINDING_ACTIVE"
    BUDGET_FOLDER_BOUND = "BUDGET_FOLDER_BOUND"
    SOURCE_EXISTS = "SOURCE_EXISTS"
    SOURCE_VERSION_IDENTIFIED = "SOURCE_VERSION_IDENTIFIED"
    FORMAT_SUPPORTED = "FORMAT_SUPPORTED"
    SCHEMA_MAPPED = "SCHEMA_MAPPED"
    BUSINESS_PROFILE_PINNED = "BUSINESS_PROFILE_PINNED"
    MARKETS_RESOLVED = "MARKETS_RESOLVED"
    CHANNELS_RESOLVED = "CHANNELS_RESOLVED"
    QUARTERS_VALID = "QUARTERS_VALID"
    AMOUNTS_NONNEGATIVE = "AMOUNTS_NONNEGATIVE"
    BLANKS_ACKNOWLEDGED = "BLANKS_ACKNOWLEDGED"
    DUPLICATES_RESOLVED = "DUPLICATES_RESOLVED"
    MIXED_GRAIN_RESOLVED = "MIXED_GRAIN_RESOLVED"
    CURRENCY_SINGLE = "CURRENCY_SINGLE"
    DECLARED_TOTAL_RECONCILED = "DECLARED_TOTAL_RECONCILED"
    SOURCE_UNCHANGED = "SOURCE_UNCHANGED"
    CANONICAL_MARKET_CONTRACT = "CANONICAL_MARKET_CONTRACT"


class RowBudgetStatus(StrEnum):
    PLANNED = "PLANNED"
    COMMITTED = "COMMITTED"
    FLEXIBLE = "FLEXIBLE"


class InvestmentPlanReadyStatus(StrEnum):
    NOT_SET = "NOT_SET"
    PENDING = "PENDING"
    INVESTMENT_PLAN_READY = "INVESTMENT_PLAN_READY"
    SOURCE_STALE = "SOURCE_STALE"


class EvidenceCoverageLabel(StrEnum):
    MMM = "MMM"
    MTA = "MTA"
    EXPERIMENT = "EXPERIMENT"
    BRAND = "BRAND"
    EXPOSURE_INTEGRITY = "EXPOSURE_INTEGRITY"
    NONE = "NONE"


class ExposureGuardrailRole(StrEnum):
    MODEL_INPUT = "MODEL_INPUT"
    CONSTRAINT = "CONSTRAINT"
    SCENARIO_GUARDRAIL = "SCENARIO_GUARDRAIL"
    APPROVAL_GUARDRAIL = "APPROVAL_GUARDRAIL"


class DriveBudgetFolderKind(StrEnum):
    BUDGETS = "BUDGETS"
    TEMPLATES = "TEMPLATES"
    PLANS = "PLANS"
    SCENARIOS = "SCENARIOS"
    PROPOSALS = "PROPOSALS"
