"""Optimization vocabulary. Native Meridian first; CVaR later."""

from __future__ import annotations

from enum import StrEnum


class OptimizationProposalStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    SCENARIO = "SCENARIO"
    RECOMMENDED = "RECOMMENDED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class OptimizationSolverKind(StrEnum):
    MERIDIAN_NATIVE_FIXED_BUDGET = "MERIDIAN_NATIVE_FIXED_BUDGET"
    MERIDIAN_NATIVE_FLEXIBLE_BUDGET = "MERIDIAN_NATIVE_FLEXIBLE_BUDGET"
    PREM3_RISK_AWARE_FRONTIER = "PREM3_RISK_AWARE_FRONTIER"


class OptimizationReadinessStatus(StrEnum):
    NOT_READY = "NOT_READY"
    OPTIMIZATION_READY = "OPTIMIZATION_READY"
    REQUIRES_ACCEPTED_MMM = "REQUIRES_ACCEPTED_MMM"
    REQUIRES_SUPPORTED_MAPPING = "REQUIRES_SUPPORTED_MAPPING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    STALE = "STALE"


class OptimizationObjectiveKind(StrEnum):
    EXPECTED_KPI = "EXPECTED_KPI"
    EXPECTED_REVENUE = "EXPECTED_REVENUE"
    TARGET_ROI = "TARGET_ROI"
    MARGINAL_ROI = "MARGINAL_ROI"
    PREM3_CVAR = "PREM3_CVAR"


class MappingAuthority(StrEnum):
    MODEL_CONTRACT_EXACT = "MODEL_CONTRACT_EXACT"
    CANONICAL_CHANNEL_BINDING = "CANONICAL_CHANNEL_BINDING"
    CANONICAL_MARKET_BINDING = "CANONICAL_MARKET_BINDING"
    USER_CONFIRMED = "USER_CONFIRMED"
    APPROVED_CUSTOM_MAPPING = "APPROVED_CUSTOM_MAPPING"


class ForbiddenMappingAuthority(StrEnum):
    FUZZY_NAME = "FUZZY_NAME"
    STRING_SIMILARITY = "STRING_SIMILARITY"
    LLM_INFERRED = "LLM_INFERRED"


class MappingKind(StrEnum):
    ONE_TO_ONE = "ONE_TO_ONE"
    MANY_TO_ONE = "MANY_TO_ONE"
    ONE_TO_MANY = "ONE_TO_MANY"
    MANY_TO_MANY = "MANY_TO_MANY"


class MappingEntryStatus(StrEnum):
    MAPPED = "MAPPED"
    UNMAPPED = "UNMAPPED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CONFLICT = "CONFLICT"
    AUTO_SAFE = "AUTO_SAFE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    EXCLUDED = "EXCLUDED"
    FIXED = "FIXED"


class PortfolioModelMappingStatus(StrEnum):
    COMPLETE = "COMPLETE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"
    CONFLICT = "CONFLICT"


class MarketModelCompatibility(StrEnum):
    DIRECTLY_MODELED = "DIRECTLY_MODELED"
    AGGREGATED_IN_MODEL = "AGGREGATED_IN_MODEL"
    NOT_MODELED = "NOT_MODELED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ModelGeoSemantics(StrEnum):
    NATIONAL = "NATIONAL"
    GEO = "GEO"
    MARKET_FILTERED = "MARKET_FILTERED"
    MULTI_MARKET = "MULTI_MARKET"


class ModelVariableRole(StrEnum):
    MEDIA_SPEND = "MEDIA_SPEND"
    EXECUTION = "EXECUTION"
    CONTROL = "CONTROL"
    ORGANIC = "ORGANIC"
    OUTCOME = "OUTCOME"
    CONTEXT = "CONTEXT"


class ModelVariableOptimizationEligibility(StrEnum):
    OPTIMIZABLE = "OPTIMIZABLE"
    FIXED = "FIXED"
    CONTEXT_ONLY = "CONTEXT_ONLY"
    CONTROL = "CONTROL"
    OUTCOME = "OUTCOME"
    UNSUPPORTED = "UNSUPPORTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class SpendSemantics(StrEnum):
    APPROVED_MEDIA_SPEND = "APPROVED_MEDIA_SPEND"
    NET_MEDIA_SPEND = "NET_MEDIA_SPEND"
    GROSS_MEDIA_COST = "GROSS_MEDIA_COST"
    COMMITTED_CONTRACT_VALUE = "COMMITTED_CONTRACT_VALUE"
    IMPRESSIONS = "IMPRESSIONS"


class MappingCardinalityPolicy(StrEnum):
    AGGREGATE_FOR_MODEL = "AGGREGATE_FOR_MODEL"
    APPROVED_ALLOCATION_SPLIT = "APPROVED_ALLOCATION_SPLIT"
    FIXED_AT_ZERO = "FIXED_AT_ZERO"
    FIXED_BASELINE = "FIXED_BASELINE"
    EXCLUDED = "EXCLUDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class UnmappedVariableTreatment(StrEnum):
    FIXED_AT_ZERO = "FIXED_AT_ZERO"
    FIXED_BASELINE = "FIXED_BASELINE"
    EXCLUDED = "EXCLUDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class OptimizationIssueCode(StrEnum):
    NO_ACCEPTED_MODEL = "NO_ACCEPTED_MODEL"
    MULTIPLE_ACCEPTED_MODELS = "MULTIPLE_ACCEPTED_MODELS"
    MODEL_CONSUMPTION_CONTRACT_INCOMPLETE = "MODEL_CONSUMPTION_CONTRACT_INCOMPLETE"
    MODEL_CONSUMPTION_PROJECTION_STALE = "MODEL_CONSUMPTION_PROJECTION_STALE"
    PORTFOLIO_CHANNEL_NOT_MODELED = "PORTFOLIO_CHANNEL_NOT_MODELED"
    MODEL_VARIABLE_WITHOUT_PORTFOLIO_ALLOCATION = "MODEL_VARIABLE_WITHOUT_PORTFOLIO_ALLOCATION"
    MARKET_NOT_MODELED = "MARKET_NOT_MODELED"
    MARKET_SCOPE_TOO_GRANULAR = "MARKET_SCOPE_TOO_GRANULAR"
    PERIOD_COMPATIBILITY_REVIEW_REQUIRED = "PERIOD_COMPATIBILITY_REVIEW_REQUIRED"
    CURRENCY_COMPATIBILITY_REVIEW_REQUIRED = "CURRENCY_COMPATIBILITY_REVIEW_REQUIRED"
    SPEND_SEMANTICS_MISMATCH = "SPEND_SEMANTICS_MISMATCH"
    MODEL_VARIABLE_NOT_OPTIMIZABLE = "MODEL_VARIABLE_NOT_OPTIMIZABLE"
    ONE_TO_MANY_MAPPING_REQUIRES_SPLIT = "ONE_TO_MANY_MAPPING_REQUIRES_SPLIT"
    MANY_TO_ONE_MAPPING_REDUCES_CONTROL = "MANY_TO_ONE_MAPPING_REDUCES_CONTROL"
    MANY_TO_MANY_MAPPING_UNSUPPORTED = "MANY_TO_MANY_MAPPING_UNSUPPORTED"
    OPTIMIZER_INPUT_ARTIFACT_MISSING = "OPTIMIZER_INPUT_ARTIFACT_MISSING"
    MODEL_RUNTIME_INCOMPATIBLE = "MODEL_RUNTIME_INCOMPATIBLE"
    STALE_READINESS_RECEIPT = "STALE_READINESS_RECEIPT"
    APPROVED_PLAN_REQUIRED = "APPROVED_PLAN_REQUIRED"
    ACTUALS_NEVER_REPLACE_APPROVED_BASELINE = "ACTUALS_NEVER_REPLACE_APPROVED_BASELINE"
    FUZZY_MAPPING_NOT_AUTHORITY = "FUZZY_MAPPING_NOT_AUTHORITY"
    CROSS_PROJECT_MODEL_MAPPING = "CROSS_PROJECT_MODEL_MAPPING"
    CROSS_TENANT_MODEL_MAPPING = "CROSS_TENANT_MODEL_MAPPING"
    CLIENT_SUPPLIED_TENANT = "CLIENT_SUPPLIED_TENANT"
    CLIENT_SUPPLIED_ARTIFACT_LOCATION = "CLIENT_SUPPLIED_ARTIFACT_LOCATION"
    MTA_NOT_CAUSAL_AUTHORITY = "MTA_NOT_CAUSAL_AUTHORITY"
    OBSERVATION_BLOCKER = "OBSERVATION_BLOCKER"


class OptimizationReadinessCheckCode(StrEnum):
    APPROVED_PLAN_AVAILABLE = "APPROVED_PLAN_AVAILABLE"
    PORTFOLIO_SNAPSHOT_VALID = "PORTFOLIO_SNAPSHOT_VALID"
    MODEL_ACCEPTED = "MODEL_ACCEPTED"
    MODEL_CONSUMPTION_CONTRACT_VALID = "MODEL_CONSUMPTION_CONTRACT_VALID"
    MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE = "MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE"
    MARKET_COMPATIBLE = "MARKET_COMPATIBLE"
    CHANNEL_MAPPING_COMPLETE = "CHANNEL_MAPPING_COMPLETE"
    PERIOD_COMPATIBLE = "PERIOD_COMPATIBLE"
    CURRENCY_COMPATIBLE = "CURRENCY_COMPATIBLE"
    SPEND_SEMANTICS_COMPATIBLE = "SPEND_SEMANTICS_COMPATIBLE"
    OPTIMIZABLE_VARIABLES_VALID = "OPTIMIZABLE_VARIABLES_VALID"
    NO_UNRESOLVED_MAPPING_CONFLICTS = "NO_UNRESOLVED_MAPPING_CONFLICTS"
    INPUT_CONTRACT_FINGERPRINTED = "INPUT_CONTRACT_FINGERPRINTED"


class OptimizationEvidenceCoverageStatus(StrEnum):
    COVERED = "COVERED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class OptimizationInputStatus(StrEnum):
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"


class BudgetResolutionPath(StrEnum):
    APPROVED_DRIVE_PLAN_TRANSIENT_VIEW = "APPROVED_DRIVE_PLAN_TRANSIENT_VIEW"


class OptimizationRunKind(StrEnum):
    FIXED_BUDGET = "FIXED_BUDGET"


class OptimizationRunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    READBACK = "READBACK"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    STALE_REFUSED = "STALE_REFUSED"


class OptimizationExecutionPhase(StrEnum):
    REVALIDATE = "REVALIDATE"
    RESOLVE_BUDGET = "RESOLVE_BUDGET"
    LOAD_MODEL = "LOAD_MODEL"
    OPTIMIZE = "OPTIMIZE"
    VALIDATE = "VALIDATE"
    PERSIST = "PERSIST"
    READBACK = "READBACK"


class OptimizationFailureClass(StrEnum):
    OPTIMIZATION_NOT_READY = "OPTIMIZATION_NOT_READY"
    OPTIMIZATION_REVIEW_REQUIRED = "OPTIMIZATION_REVIEW_REQUIRED"
    OPTIMIZATION_READINESS_STALE = "OPTIMIZATION_READINESS_STALE"
    APPROVED_PLAN_REQUIRED = "APPROVED_PLAN_REQUIRED"
    UNAPPROVED_PLAN = "UNAPPROVED_PLAN"
    ACTUALS_NOT_FIXED_BUDGET = "ACTUALS_NOT_FIXED_BUDGET"
    CLIENT_BUDGET_ARRAY_REJECTED = "CLIENT_BUDGET_ARRAY_REJECTED"
    MODEL_ARTIFACT_UNAVAILABLE = "MODEL_ARTIFACT_UNAVAILABLE"
    NATIVE_OPTIMIZER_FAILED = "NATIVE_OPTIMIZER_FAILED"
    MERIDIAN_OPTIMIZER_API_REVIEW_REQUIRED = "MERIDIAN_OPTIMIZER_API_REVIEW_REQUIRED"
    OPTIMIZER_RESULT_INVALID = "OPTIMIZER_RESULT_INVALID"
    OPTIMIZER_BUDGET_INVARIANT_FAILED = "OPTIMIZER_BUDGET_INVARIANT_FAILED"
    RESULT_READBACK_FAILED = "RESULT_READBACK_FAILED"
    FLEXIBLE_BUDGET_NOT_IMPLEMENTED = "FLEXIBLE_BUDGET_NOT_IMPLEMENTED"


class OptimizationRetrySemantics(StrEnum):
    NOT_RETRYABLE = "NOT_RETRYABLE"
    IDEMPOTENT_RETRY = "IDEMPOTENT_RETRY"
    NEW_RUN_REQUIRED = "NEW_RUN_REQUIRED"


class OptimizationAmountKind(StrEnum):
    MODEL_RECOMMENDED = "MODEL_RECOMMENDED"
    MODEL_ESTIMATE = "MODEL_ESTIMATE"


class OptimizerConstraintStatus(StrEnum):
    WITHIN_BOUNDS = "WITHIN_BOUNDS"
    AT_LOWER = "AT_LOWER"
    AT_UPPER = "AT_UPPER"
    UNKNOWN = "UNKNOWN"


ORGANIC_CHANNEL_IDS: frozenset[str] = frozenset({"search_organic", "social_organic"})
POLICY_VERSION = "p6-04/v1"
EXECUTION_POLICY_VERSION = "p6-05/v1"
PINNED_MERIDIAN_RUNTIME = "1.8.0"
PINNED_SPEND_CONSTRAINT_LOWER = 0.3
PINNED_SPEND_CONSTRAINT_UPPER = 0.3
PINNED_OPTIMIZER_GTOL = 0.0001
ARTIFACT_SCHEMA_VERSION = "p6-05/v1"

RUNNING_OPTIMIZATION_STATUSES: frozenset[OptimizationRunStatus] = frozenset(
    {
        OptimizationRunStatus.CREATED,
        OptimizationRunStatus.QUEUED,
        OptimizationRunStatus.DISPATCHED,
        OptimizationRunStatus.RUNNING,
        OptimizationRunStatus.VALIDATING,
        OptimizationRunStatus.READBACK,
    }
)

REQUIRED_READINESS_CHECKS: tuple[OptimizationReadinessCheckCode, ...] = (
    OptimizationReadinessCheckCode.APPROVED_PLAN_AVAILABLE,
    OptimizationReadinessCheckCode.PORTFOLIO_SNAPSHOT_VALID,
    OptimizationReadinessCheckCode.MODEL_ACCEPTED,
    OptimizationReadinessCheckCode.MODEL_CONSUMPTION_CONTRACT_VALID,
    OptimizationReadinessCheckCode.MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE,
    OptimizationReadinessCheckCode.MARKET_COMPATIBLE,
    OptimizationReadinessCheckCode.CHANNEL_MAPPING_COMPLETE,
    OptimizationReadinessCheckCode.PERIOD_COMPATIBLE,
    OptimizationReadinessCheckCode.CURRENCY_COMPATIBLE,
    OptimizationReadinessCheckCode.SPEND_SEMANTICS_COMPATIBLE,
    OptimizationReadinessCheckCode.OPTIMIZABLE_VARIABLES_VALID,
    OptimizationReadinessCheckCode.NO_UNRESOLVED_MAPPING_CONFLICTS,
    OptimizationReadinessCheckCode.INPUT_CONTRACT_FINGERPRINTED,
)

BLOCKING_OBSERVATION_TYPES: frozenset[str] = frozenset(
    {
        "CURRENCY_MISMATCH",
        "PERIOD_MAPPING_REQUIRED",
        "UNRESOLVED_MARKET",
        "UNRESOLVED_CHANNEL",
    }
)

COMPATIBLE_SPEND_SEMANTICS: frozenset[SpendSemantics] = frozenset(
    {
        SpendSemantics.APPROVED_MEDIA_SPEND,
        SpendSemantics.NET_MEDIA_SPEND,
    }
)

GOVERNED_OVERRIDE_AUTHORITIES: frozenset[MappingAuthority] = frozenset(
    {
        MappingAuthority.USER_CONFIRMED,
        MappingAuthority.APPROVED_CUSTOM_MAPPING,
    }
)
