"""Optimization vocabulary. Native Meridian first; CVaR later."""

from __future__ import annotations

from enum import StrEnum


class OptimizationProposalStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    SCENARIO = "SCENARIO"
    RECOMMENDED = "RECOMMENDED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class OptimizationSolverKind(StrEnum):
    MERIDIAN_NATIVE_FIXED_BUDGET = "MERIDIAN_NATIVE_FIXED_BUDGET"
    MERIDIAN_NATIVE_FLEXIBLE_BUDGET = "MERIDIAN_NATIVE_FLEXIBLE_BUDGET"
    PREM3_RISK_AWARE_FRONTIER = "PREM3_RISK_AWARE_FRONTIER"


class OptimizationReadinessStatus(StrEnum):
    NOT_READY = "NOT_READY"
    OPTIMIZATION_READY = "OPTIMIZATION_READY"
    REQUIRES_ACCEPTED_MMM = "REQUIRES_ACCEPTED_MMM"
    REQUIRES_SUPPORTED_MAPPING = "REQUIRES_SUPPORTED_MAPPING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    STALE = "STALE"


class OptimizationObjectiveKind(StrEnum):
    EXPECTED_KPI = "EXPECTED_KPI"
    EXPECTED_REVENUE = "EXPECTED_REVENUE"
    TARGET_ROI = "TARGET_ROI"
    MARGINAL_ROI = "MARGINAL_ROI"
    PREM3_CVAR = "PREM3_CVAR"


class OptimizationObjectiveMode(StrEnum):
    MAX_EXPECTED_OUTCOME_FIXED_BUDGET = "MAX_EXPECTED_OUTCOME_FIXED_BUDGET"
    TARGET_ROI_FLEXIBLE_BUDGET = "TARGET_ROI_FLEXIBLE_BUDGET"
    TARGET_MROI_FLEXIBLE_BUDGET = "TARGET_MROI_FLEXIBLE_BUDGET"
    MAX_INCREMENTAL_CONTRIBUTION_VALUE = "MAX_INCREMENTAL_CONTRIBUTION_VALUE"


class OptimizationBudgetMode(StrEnum):
    FIXED = "FIXED"
    FLEXIBLE = "FLEXIBLE"


class ConstraintFamily(StrEnum):
    TOTAL_FIXED_BUDGET = "TOTAL_FIXED_BUDGET"
    TOTAL_FLEXIBLE_BUDGET = "TOTAL_FLEXIBLE_BUDGET"
    LINE_MIN = "LINE_MIN"
    LINE_MAX = "LINE_MAX"
    LOCKED_ALLOCATION = "LOCKED_ALLOCATION"
    MAX_ABSOLUTE_MOVE = "MAX_ABSOLUTE_MOVE"
    MAX_PERCENT_MOVE = "MAX_PERCENT_MOVE"
    MARKET_FLOOR = "MARKET_FLOOR"
    MARKET_CEILING = "MARKET_CEILING"
    QUARTER_FLOOR = "QUARTER_FLOOR"
    QUARTER_CEILING = "QUARTER_CEILING"
    FUNNEL_FLOOR = "FUNNEL_FLOOR"
    FUNNEL_CEILING = "FUNNEL_CEILING"
    EXPERIMENT_RESERVE = "EXPERIMENT_RESERVE"
    CONTINGENCY_RESERVE = "CONTINGENCY_RESERVE"
    AVAILABILITY_WINDOW = "AVAILABILITY_WINDOW"


class ConstraintAuthority(StrEnum):
    HUMAN_CONFIRMED = "HUMAN_CONFIRMED"
    BUSINESS_IQ_GOVERNED = "BUSINESS_IQ_GOVERNED"
    CONTRACTUAL = "CONTRACTUAL"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"


class AssumptionAuthority(StrEnum):
    HUMAN_CONFIRMED = "HUMAN_CONFIRMED"
    BUSINESS_IQ_GOVERNED = "BUSINESS_IQ_GOVERNED"
    CONTRACTUAL = "CONTRACTUAL"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"


class AssumptionStatus(StrEnum):
    PINNED = "PINNED"
    STALE = "STALE"
    INVALID = "INVALID"


class MediaUnitCostKind(StrEnum):
    CPM = "CPM"
    COST_PER_CLICK = "COST_PER_CLICK"
    COST_PER_IMPRESSION = "COST_PER_IMPRESSION"
    COST_PER_REACH_UNIT = "COST_PER_REACH_UNIT"
    OTHER_MODEL_COMPATIBLE = "OTHER_MODEL_COMPATIBLE"


class UnsupportedChannelPolicy(StrEnum):
    HOLD_BASELINE = "HOLD_BASELINE"
    RESERVE_EXPERIMENT_AMOUNT = "RESERVE_EXPERIMENT_AMOUNT"
    EXCLUDE_FROM_OPTIMIZER_BUT_KEEP_PORTFOLIO = "EXCLUDE_FROM_OPTIMIZER_BUT_KEEP_PORTFOLIO"
    APPROVED_PROXY_WITH_REVIEW = "APPROVED_PROXY_WITH_REVIEW"


class ConstraintValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    INFEASIBLE = "INFEASIBLE"


class AdvancedOptimizationReadinessStatus(StrEnum):
    NOT_READY = "NOT_READY"
    ADVANCED_OPTIMIZATION_READY = "ADVANCED_OPTIMIZATION_READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    STALE = "STALE"


class MappingAuthority(StrEnum):
    MODEL_CONTRACT_EXACT = "MODEL_CONTRACT_EXACT"
    CANONICAL_CHANNEL_BINDING = "CANONICAL_CHANNEL_BINDING"
    CANONICAL_MARKET_BINDING = "CANONICAL_MARKET_BINDING"
    USER_CONFIRMED = "USER_CONFIRMED"
    APPROVED_CUSTOM_MAPPING = "APPROVED_CUSTOM_MAPPING"


class ForbiddenMappingAuthority(StrEnum):
    FUZZY_NAME = "FUZZY_NAME"
    STRING_SIMILARITY = "STRING_SIMILARITY"
    LLM_INFERRED = "LLM_INFERRED"


class MappingKind(StrEnum):
    ONE_TO_ONE = "ONE_TO_ONE"
    MANY_TO_ONE = "MANY_TO_ONE"
    ONE_TO_MANY = "ONE_TO_MANY"
    MANY_TO_MANY = "MANY_TO_MANY"


class MappingEntryStatus(StrEnum):
    MAPPED = "MAPPED"
    UNMAPPED = "UNMAPPED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    CONFLICT = "CONFLICT"
    AUTO_SAFE = "AUTO_SAFE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    EXCLUDED = "EXCLUDED"
    FIXED = "FIXED"


class PortfolioModelMappingStatus(StrEnum):
    COMPLETE = "COMPLETE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"
    CONFLICT = "CONFLICT"


class MarketModelCompatibility(StrEnum):
    DIRECTLY_MODELED = "DIRECTLY_MODELED"
    AGGREGATED_IN_MODEL = "AGGREGATED_IN_MODEL"
    NOT_MODELED = "NOT_MODELED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ModelGeoSemantics(StrEnum):
    NATIONAL = "NATIONAL"
    GEO = "GEO"
    MARKET_FILTERED = "MARKET_FILTERED"
    MULTI_MARKET = "MULTI_MARKET"


class ModelVariableRole(StrEnum):
    MEDIA_SPEND = "MEDIA_SPEND"
    EXECUTION = "EXECUTION"
    CONTROL = "CONTROL"
    ORGANIC = "ORGANIC"
    OUTCOME = "OUTCOME"
    CONTEXT = "CONTEXT"


class ModelVariableOptimizationEligibility(StrEnum):
    OPTIMIZABLE = "OPTIMIZABLE"
    FIXED = "FIXED"
    CONTEXT_ONLY = "CONTEXT_ONLY"
    CONTROL = "CONTROL"
    OUTCOME = "OUTCOME"
    UNSUPPORTED = "UNSUPPORTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class SpendSemantics(StrEnum):
    APPROVED_MEDIA_SPEND = "APPROVED_MEDIA_SPEND"
    NET_MEDIA_SPEND = "NET_MEDIA_SPEND"
    GROSS_MEDIA_COST = "GROSS_MEDIA_COST"
    COMMITTED_CONTRACT_VALUE = "COMMITTED_CONTRACT_VALUE"
    IMPRESSIONS = "IMPRESSIONS"


class MappingCardinalityPolicy(StrEnum):
    AGGREGATE_FOR_MODEL = "AGGREGATE_FOR_MODEL"
    APPROVED_ALLOCATION_SPLIT = "APPROVED_ALLOCATION_SPLIT"
    FIXED_AT_ZERO = "FIXED_AT_ZERO"
    FIXED_BASELINE = "FIXED_BASELINE"
    EXCLUDED = "EXCLUDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class UnmappedVariableTreatment(StrEnum):
    FIXED_AT_ZERO = "FIXED_AT_ZERO"
    FIXED_BASELINE = "FIXED_BASELINE"
    EXCLUDED = "EXCLUDED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class OptimizationIssueCode(StrEnum):
    NO_ACCEPTED_MODEL = "NO_ACCEPTED_MODEL"
    MULTIPLE_ACCEPTED_MODELS = "MULTIPLE_ACCEPTED_MODELS"
    MODEL_CONSUMPTION_CONTRACT_INCOMPLETE = "MODEL_CONSUMPTION_CONTRACT_INCOMPLETE"
    MODEL_CONSUMPTION_PROJECTION_STALE = "MODEL_CONSUMPTION_PROJECTION_STALE"
    PORTFOLIO_CHANNEL_NOT_MODELED = "PORTFOLIO_CHANNEL_NOT_MODELED"
    MODEL_VARIABLE_WITHOUT_PORTFOLIO_ALLOCATION = "MODEL_VARIABLE_WITHOUT_PORTFOLIO_ALLOCATION"
    MARKET_NOT_MODELED = "MARKET_NOT_MODELED"
    MARKET_SCOPE_TOO_GRANULAR = "MARKET_SCOPE_TOO_GRANULAR"
    PERIOD_COMPATIBILITY_REVIEW_REQUIRED = "PERIOD_COMPATIBILITY_REVIEW_REQUIRED"
    CURRENCY_COMPATIBILITY_REVIEW_REQUIRED = "CURRENCY_COMPATIBILITY_REVIEW_REQUIRED"
    SPEND_SEMANTICS_MISMATCH = "SPEND_SEMANTICS_MISMATCH"
    MODEL_VARIABLE_NOT_OPTIMIZABLE = "MODEL_VARIABLE_NOT_OPTIMIZABLE"
    ONE_TO_MANY_MAPPING_REQUIRES_SPLIT = "ONE_TO_MANY_MAPPING_REQUIRES_SPLIT"
    MANY_TO_ONE_MAPPING_REDUCES_CONTROL = "MANY_TO_ONE_MAPPING_REDUCES_CONTROL"
    MANY_TO_MANY_MAPPING_UNSUPPORTED = "MANY_TO_MANY_MAPPING_UNSUPPORTED"
    OPTIMIZER_INPUT_ARTIFACT_MISSING = "OPTIMIZER_INPUT_ARTIFACT_MISSING"
    MODEL_RUNTIME_INCOMPATIBLE = "MODEL_RUNTIME_INCOMPATIBLE"
    STALE_READINESS_RECEIPT = "STALE_READINESS_RECEIPT"
    FINANCIAL_VALUE_ASSUMPTION_REQUIRED = "FINANCIAL_VALUE_ASSUMPTION_REQUIRED"
    FUNNEL_MAPPING_REQUIRED = "FUNNEL_MAPPING_REQUIRED"
    CONSTRAINT_SET_INFEASIBLE = "CONSTRAINT_SET_INFEASIBLE"
    CONSTRAINT_REFERENCE_INVALID = "CONSTRAINT_REFERENCE_INVALID"
    UNSUPPORTED_CHANNEL_POLICY_REQUIRED = "UNSUPPORTED_CHANNEL_POLICY_REQUIRED"
    PROXY_APPROVAL_REQUIRED = "PROXY_APPROVAL_REQUIRED"
    EXPOSURE_GUARDRAIL_NOT_IN_P6_07 = "EXPOSURE_GUARDRAIL_NOT_IN_P6_07"
    APPROVED_PLAN_REQUIRED = "APPROVED_PLAN_REQUIRED"
    ACTUALS_NEVER_REPLACE_APPROVED_BASELINE = "ACTUALS_NEVER_REPLACE_APPROVED_BASELINE"
    FUZZY_MAPPING_NOT_AUTHORITY = "FUZZY_MAPPING_NOT_AUTHORITY"
    CROSS_PROJECT_MODEL_MAPPING = "CROSS_PROJECT_MODEL_MAPPING"
    CROSS_TENANT_MODEL_MAPPING = "CROSS_TENANT_MODEL_MAPPING"
    CLIENT_SUPPLIED_TENANT = "CLIENT_SUPPLIED_TENANT"
    CLIENT_SUPPLIED_ARTIFACT_LOCATION = "CLIENT_SUPPLIED_ARTIFACT_LOCATION"
    MTA_NOT_CAUSAL_AUTHORITY = "MTA_NOT_CAUSAL_AUTHORITY"
    OBSERVATION_BLOCKER = "OBSERVATION_BLOCKER"


class OptimizationReadinessCheckCode(StrEnum):
    APPROVED_PLAN_AVAILABLE = "APPROVED_PLAN_AVAILABLE"
    PORTFOLIO_SNAPSHOT_VALID = "PORTFOLIO_SNAPSHOT_VALID"
    MODEL_ACCEPTED = "MODEL_ACCEPTED"
    MODEL_CONSUMPTION_CONTRACT_VALID = "MODEL_CONSUMPTION_CONTRACT_VALID"
    MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE = "MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE"
    MARKET_COMPATIBLE = "MARKET_COMPATIBLE"
    CHANNEL_MAPPING_COMPLETE = "CHANNEL_MAPPING_COMPLETE"
    PERIOD_COMPATIBLE = "PERIOD_COMPATIBLE"
    CURRENCY_COMPATIBLE = "CURRENCY_COMPATIBLE"
    SPEND_SEMANTICS_COMPATIBLE = "SPEND_SEMANTICS_COMPATIBLE"
    OPTIMIZABLE_VARIABLES_VALID = "OPTIMIZABLE_VARIABLES_VALID"
    NO_UNRESOLVED_MAPPING_CONFLICTS = "NO_UNRESOLVED_MAPPING_CONFLICTS"
    INPUT_CONTRACT_FINGERPRINTED = "INPUT_CONTRACT_FINGERPRINTED"
    ASSUMPTIONS_PINNED = "ASSUMPTIONS_PINNED"
    CONSTRAINTS_FEASIBLE = "CONSTRAINTS_FEASIBLE"
    OBJECTIVE_VALID = "OBJECTIVE_VALID"
    UNSUPPORTED_LINES_EXPLICIT = "UNSUPPORTED_LINES_EXPLICIT"
    RUNTIME_PINNED = "RUNTIME_PINNED"


class OptimizationEvidenceCoverageStatus(StrEnum):
    COVERED = "COVERED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class OptimizationInputStatus(StrEnum):
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"


class BudgetResolutionPath(StrEnum):
    APPROVED_DRIVE_PLAN_TRANSIENT_VIEW = "APPROVED_DRIVE_PLAN_TRANSIENT_VIEW"


class OptimizationRunKind(StrEnum):
    FIXED_BUDGET = "FIXED_BUDGET"
    FLEXIBLE_BUDGET = "FLEXIBLE_BUDGET"


class OptimizationRunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    READBACK = "READBACK"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    STALE_REFUSED = "STALE_REFUSED"


class OptimizationExecutionPhase(StrEnum):
    REVALIDATE = "REVALIDATE"
    RESOLVE_BUDGET = "RESOLVE_BUDGET"
    LOAD_MODEL = "LOAD_MODEL"
    OPTIMIZE = "OPTIMIZE"
    VALIDATE = "VALIDATE"
    PERSIST = "PERSIST"
    READBACK = "READBACK"


class OptimizationFailureClass(StrEnum):
    OPTIMIZATION_NOT_READY = "OPTIMIZATION_NOT_READY"
    OPTIMIZATION_REVIEW_REQUIRED = "OPTIMIZATION_REVIEW_REQUIRED"
    OPTIMIZATION_READINESS_STALE = "OPTIMIZATION_READINESS_STALE"
    APPROVED_PLAN_REQUIRED = "APPROVED_PLAN_REQUIRED"
    UNAPPROVED_PLAN = "UNAPPROVED_PLAN"
    ACTUALS_NOT_FIXED_BUDGET = "ACTUALS_NOT_FIXED_BUDGET"
    CLIENT_BUDGET_ARRAY_REJECTED = "CLIENT_BUDGET_ARRAY_REJECTED"
    MODEL_ARTIFACT_UNAVAILABLE = "MODEL_ARTIFACT_UNAVAILABLE"
    NATIVE_OPTIMIZER_FAILED = "NATIVE_OPTIMIZER_FAILED"
    MERIDIAN_OPTIMIZER_API_REVIEW_REQUIRED = "MERIDIAN_OPTIMIZER_API_REVIEW_REQUIRED"
    OPTIMIZER_RESULT_INVALID = "OPTIMIZER_RESULT_INVALID"
    OPTIMIZER_BUDGET_INVARIANT_FAILED = "OPTIMIZER_BUDGET_INVARIANT_FAILED"
    RESULT_READBACK_FAILED = "RESULT_READBACK_FAILED"
    FLEXIBLE_BUDGET_NOT_IMPLEMENTED = "FLEXIBLE_BUDGET_NOT_IMPLEMENTED"
    FLEXIBLE_BUDGET_API_UNSUPPORTED = "FLEXIBLE_BUDGET_API_UNSUPPORTED"
    OBJECTIVE_NOT_SUPPORTED = "OBJECTIVE_NOT_SUPPORTED"
    FINANCIAL_VALUE_ASSUMPTION_REQUIRED = "FINANCIAL_VALUE_ASSUMPTION_REQUIRED"
    FUTURE_COST_ASSUMPTION_INVALID = "FUTURE_COST_ASSUMPTION_INVALID"
    FLIGHTING_ASSUMPTION_INVALID = "FLIGHTING_ASSUMPTION_INVALID"
    CONSTRAINT_SET_INFEASIBLE = "CONSTRAINT_SET_INFEASIBLE"
    CONSTRAINT_REFERENCE_INVALID = "CONSTRAINT_REFERENCE_INVALID"
    CONSTRAINT_UNIT_MISMATCH = "CONSTRAINT_UNIT_MISMATCH"
    ADVANCED_READINESS_STALE = "ADVANCED_READINESS_STALE"
    RESULT_CONSTRAINT_VIOLATION = "RESULT_CONSTRAINT_VIOLATION"
    RISK_NEUTRAL_PARITY_FAILED = "RISK_NEUTRAL_PARITY_FAILED"
    RISK_POLICY_INVALID = "RISK_POLICY_INVALID"
    RISK_INPUT_NOT_READY = "RISK_INPUT_NOT_READY"
    POSTERIOR_RISK_UNAVAILABLE = "POSTERIOR_RISK_UNAVAILABLE"
    SCENARIO_RISK_UNAVAILABLE = "SCENARIO_RISK_UNAVAILABLE"
    EXPOSURE_RISK_NOT_QUALIFIED = "EXPOSURE_RISK_NOT_QUALIFIED"
    CANDIDATE_GENERATION_FAILED = "CANDIDATE_GENERATION_FAILED"
    CANDIDATE_INFEASIBLE = "CANDIDATE_INFEASIBLE"
    INSUFFICIENT_FRONTIER_CANDIDATES = "INSUFFICIENT_FRONTIER_CANDIDATES"
    FRONTIER_DOMINANCE_POLICY_INVALID = "FRONTIER_DOMINANCE_POLICY_INVALID"
    FRONTIER_SELECTION_NOT_ALLOWED = "FRONTIER_SELECTION_NOT_ALLOWED"
    RISK_ARTIFACT_FINGERPRINT_MISMATCH = "RISK_ARTIFACT_FINGERPRINT_MISMATCH"


class RiskTaxonomyClass(StrEnum):
    POSTERIOR = "POSTERIOR"
    SCENARIO = "SCENARIO"
    EXPOSURE_DELIVERY = "EXPOSURE_DELIVERY"
    MODEL = "MODEL"
    DATA = "DATA"
    CONCENTRATION = "CONCENTRATION"
    EXECUTION = "EXECUTION"
    OPTIMIZATION = "OPTIMIZATION"


class RiskPosture(StrEnum):
    EXPECTED_OUTCOME = "EXPECTED_OUTCOME"
    BALANCED = "BALANCED"
    CONSERVATIVE = "CONSERVATIVE"


class FrontierSelectionState(StrEnum):
    MODEL_RECOMMENDED = "MODEL_RECOMMENDED"


class CandidateGenerationPolicy(StrEnum):
    NATIVE_OPTIMUM_PLUS_FEASIBLE_NEIGHBORS = "NATIVE_OPTIMUM_PLUS_FEASIBLE_NEIGHBORS"


class RiskBaselineKind(StrEnum):
    APPROVED_PLAN = "APPROVED_PLAN"
    ACTUAL_YTD = "ACTUAL_YTD"
    FORECAST_AT_COMPLETION = "FORECAST_AT_COMPLETION"
    TRANSIENT_SCENARIO = "TRANSIENT_SCENARIO"


class DominanceSense(StrEnum):
    MAXIMIZE = "MAXIMIZE"
    MINIMIZE = "MINIMIZE"


class DominanceMetric(StrEnum):
    EXPECTED_OUTCOME = "EXPECTED_OUTCOME"
    DOWNSIDE_TAIL = "DOWNSIDE_TAIL"
    CONCENTRATION_HHI = "CONCENTRATION_HHI"
    STABILITY_L1 = "STABILITY_L1"


class ConcentrationDimension(StrEnum):
    CHANNEL = "CHANNEL"
    MARKET = "MARKET"
    PROVIDER = "PROVIDER"


class LossDefinition(StrEnum):
    BASELINE_MINUS_CANDIDATE_OUTCOME = "BASELINE_MINUS_CANDIDATE_OUTCOME"


class RiskFrontierReadinessStatus(StrEnum):
    NOT_READY = "NOT_READY"
    RISK_FRONTIER_READY = "RISK_FRONTIER_READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class DistributionFamily(StrEnum):
    EMPIRICAL = "EMPIRICAL"
    NORMAL = "NORMAL"
    LOGNORMAL = "LOGNORMAL"
    TRIANGULAR = "TRIANGULAR"
    BETA = "BETA"
    DISCRETE = "DISCRETE"
    FIXED = "FIXED"


class DistributionAuthority(StrEnum):
    HISTORICAL_EMPIRICAL = "HISTORICAL_EMPIRICAL"
    MODEL_POSTERIOR = "MODEL_POSTERIOR"
    DATA_FOUNDATION_DERIVED = "DATA_FOUNDATION_DERIVED"
    P6_08_EXPOSURE_DERIVED = "P6_08_EXPOSURE_DERIVED"
    USER_APPROVED = "USER_APPROVED"
    BUSINESS_IQ_APPROVED = "BUSINESS_IQ_APPROVED"


class CorrelationAuthority(StrEnum):
    INDEPENDENT = "INDEPENDENT"
    EMPIRICAL_CORRELATION = "EMPIRICAL_CORRELATION"
    USER_APPROVED_CORRELATION = "USER_APPROVED_CORRELATION"
    MODEL_DERIVED = "MODEL_DERIVED"


class SimulationRunStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class OutcomeEvaluatorKind(StrEnum):
    GOVERNED_PLANNING_ECONOMICS = "GOVERNED_PLANNING_ECONOMICS"
    ACCEPTED_POSTERIOR_EVALUATION = "ACCEPTED_POSTERIOR_EVALUATION"


class OutcomeUnit(StrEnum):
    KPI = "KPI"
    INCREMENTAL_KPI = "INCREMENTAL_KPI"
    REVENUE = "REVENUE"
    INCREMENTAL_REVENUE = "INCREMENTAL_REVENUE"
    CONTRIBUTION_VALUE = "CONTRIBUTION_VALUE"


class SimulationSemanticType(StrEnum):
    FUTURE_CPM = "FUTURE_CPM"
    COST_PER_MEDIA_UNIT = "COST_PER_MEDIA_UNIT"
    CONVERSION_VALUE = "CONVERSION_VALUE"
    MARGIN_PER_KPI = "MARGIN_PER_KPI"
    DEMAND_MULTIPLIER = "DEMAND_MULTIPLIER"
    CHANNEL_MULTIPLIER = "CHANNEL_MULTIPLIER"
    VIEWABILITY = "VIEWABILITY"
    IVT = "IVT"
    IN_TARGET_RATE = "IN_TARGET_RATE"
    REACH_EFFICIENCY = "REACH_EFFICIENCY"
    FREQUENCY = "FREQUENCY"
    INVENTORY_QUALITY = "INVENTORY_QUALITY"


class OptimizationRetrySemantics(StrEnum):
    NOT_RETRYABLE = "NOT_RETRYABLE"
    IDEMPOTENT_RETRY = "IDEMPOTENT_RETRY"
    NEW_RUN_REQUIRED = "NEW_RUN_REQUIRED"


class OptimizationAmountKind(StrEnum):
    MODEL_RECOMMENDED = "MODEL_RECOMMENDED"
    MODEL_ESTIMATE = "MODEL_ESTIMATE"


class OptimizerConstraintStatus(StrEnum):
    WITHIN_BOUNDS = "WITHIN_BOUNDS"
    AT_LOWER = "AT_LOWER"
    AT_UPPER = "AT_UPPER"
    UNKNOWN = "UNKNOWN"


ORGANIC_CHANNEL_IDS: frozenset[str] = frozenset({"search_organic", "social_organic"})
POLICY_VERSION = "p6-04/v1"
EXECUTION_POLICY_VERSION = "p6-05/v1"
ADVANCED_POLICY_VERSION = "p6-07/v1"
PINNED_MERIDIAN_RUNTIME = "1.8.0"
PINNED_SPEND_CONSTRAINT_LOWER = 0.3
PINNED_SPEND_CONSTRAINT_UPPER = 0.3
PINNED_FLEXIBLE_SPEND_CONSTRAINT = 1.0
PINNED_OPTIMIZER_GTOL = 0.0001
ARTIFACT_SCHEMA_VERSION = "p6-05/v1"
ADVANCED_ARTIFACT_SCHEMA_VERSION = "p6-07/v1"
RISK_POLICY_VERSION = "p6-09/v1"
RISK_ARTIFACT_SCHEMA_VERSION = "p6-09/v1"
SIMULATION_POLICY_VERSION = "p6-09a/v1"
SIMULATION_ARTIFACT_SCHEMA_VERSION = "p6-09a/v1"
SIMULATION_ENGINE_VERSION = "p6-09a/engine/v1"
SIMULATION_MIN_DRAWS = 64
SIMULATION_MAX_DRAWS = 10_000
SIMULATION_MAX_CANDIDATES = 50
SIMULATION_MAX_VARIABLES = 32
SIMULATION_MAX_CELLS = 50_000
OUTCOME_POLICY_VERSION = "p6-10/v1"


class InvestmentDecisionKind(StrEnum):
    ACCEPT = "ACCEPT"
    ACCEPT_WITH_MODIFICATIONS = "ACCEPT_WITH_MODIFICATIONS"
    REJECT = "REJECT"
    DEFER = "DEFER"
    WITHDRAW = "WITHDRAW"
    EXPIRED = "EXPIRED"


class OutcomeLifecycleStatus(StrEnum):
    OPEN = "OPEN"
    AWAITING_EXECUTION = "AWAITING_EXECUTION"
    AWAITING_OUTCOME = "AWAITING_OUTCOME"
    PARTIAL = "PARTIAL"
    EVALUABLE = "EVALUABLE"
    CLOSED = "CLOSED"


class OutcomeSemanticType(StrEnum):
    OBSERVED_KPI = "OBSERVED_KPI"
    INCREMENTAL_KPI = "INCREMENTAL_KPI"
    OBSERVED_REVENUE = "OBSERVED_REVENUE"
    INCREMENTAL_REVENUE = "INCREMENTAL_REVENUE"
    MTA_ATTRIBUTED_CONVERSIONS = "MTA_ATTRIBUTED_CONVERSIONS"
    CAUSAL_CONVERSIONS = "CAUSAL_CONVERSIONS"


class OutcomeSourceAuthority(StrEnum):
    DATA_FOUNDATION = "DATA_FOUNDATION"
    GOVERNED_BIGQUERY = "GOVERNED_BIGQUERY"
    ACCEPTED_MEASUREMENT_ARTIFACT = "ACCEPTED_MEASUREMENT_ARTIFACT"
    APPROVED_CUSTOMER_EVIDENCE = "APPROVED_CUSTOMER_EVIDENCE"


class ExperienceBoundary(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"


class LearningCandidateType(StrEnum):
    MODEL_CALIBRATION_REVIEW = "MODEL_CALIBRATION_REVIEW"
    SCENARIO_ASSUMPTION_REVIEW = "SCENARIO_ASSUMPTION_REVIEW"
    EXPOSURE_RISK_POLICY_REVIEW = "EXPOSURE_RISK_POLICY_REVIEW"
    CONSTRAINT_POLICY_REVIEW = "CONSTRAINT_POLICY_REVIEW"
    DATA_QUALITY_REVIEW = "DATA_QUALITY_REVIEW"
    EXECUTION_FEASIBILITY_REVIEW = "EXECUTION_FEASIBILITY_REVIEW"
    NO_ACTION = "NO_ACTION"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ErrorContributorClass(StrEnum):
    RECOMMENDATION_DEVIATION = "RECOMMENDATION_DEVIATION"
    EXECUTION_DEVIATION = "EXECUTION_DEVIATION"
    EXPOSURE_DELIVERY_DEVIATION = "EXPOSURE_DELIVERY_DEVIATION"
    SCENARIO_ASSUMPTION_MISS = "SCENARIO_ASSUMPTION_MISS"
    MODEL_PREDICTION_MISS = "MODEL_PREDICTION_MISS"
    DATA_QUALITY_LIMITATION = "DATA_QUALITY_LIMITATION"
    OUTCOME_MEASUREMENT_LIMITATION = "OUTCOME_MEASUREMENT_LIMITATION"
    UNRESOLVED = "UNRESOLVED"


class PredictionErrorClass(StrEnum):
    WITHIN_EXPECTED_RANGE = "WITHIN_EXPECTED_RANGE"
    DIRECTIONAL_MISS = "DIRECTIONAL_MISS"
    MAGNITUDE_MISS = "MAGNITUDE_MISS"
    NOT_COMPUTABLE = "NOT_COMPUTABLE"


class AdherenceClass(StrEnum):
    MATCH = "MATCH"
    MODIFIED = "MODIFIED"
    INCOMPLETE = "INCOMPLETE"
    NOT_COMPUTABLE = "NOT_COMPUTABLE"


class ExecutionAdherenceStatus(StrEnum):
    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"

RUNNING_OPTIMIZATION_STATUSES: frozenset[OptimizationRunStatus] = frozenset(
    {
        OptimizationRunStatus.CREATED,
        OptimizationRunStatus.QUEUED,
        OptimizationRunStatus.DISPATCHED,
        OptimizationRunStatus.RUNNING,
        OptimizationRunStatus.VALIDATING,
        OptimizationRunStatus.READBACK,
    }
)

REQUIRED_READINESS_CHECKS: tuple[OptimizationReadinessCheckCode, ...] = (
    OptimizationReadinessCheckCode.APPROVED_PLAN_AVAILABLE,
    OptimizationReadinessCheckCode.PORTFOLIO_SNAPSHOT_VALID,
    OptimizationReadinessCheckCode.MODEL_ACCEPTED,
    OptimizationReadinessCheckCode.MODEL_CONSUMPTION_CONTRACT_VALID,
    OptimizationReadinessCheckCode.MODEL_OPTIMIZER_ARTIFACTS_AVAILABLE,
    OptimizationReadinessCheckCode.MARKET_COMPATIBLE,
    OptimizationReadinessCheckCode.CHANNEL_MAPPING_COMPLETE,
    OptimizationReadinessCheckCode.PERIOD_COMPATIBLE,
    OptimizationReadinessCheckCode.CURRENCY_COMPATIBLE,
    OptimizationReadinessCheckCode.SPEND_SEMANTICS_COMPATIBLE,
    OptimizationReadinessCheckCode.OPTIMIZABLE_VARIABLES_VALID,
    OptimizationReadinessCheckCode.NO_UNRESOLVED_MAPPING_CONFLICTS,
    OptimizationReadinessCheckCode.INPUT_CONTRACT_FINGERPRINTED,
)

BLOCKING_OBSERVATION_TYPES: frozenset[str] = frozenset(
    {
        "CURRENCY_MISMATCH",
        "PERIOD_MAPPING_REQUIRED",
        "UNRESOLVED_MARKET",
        "UNRESOLVED_CHANNEL",
    }
)

COMPATIBLE_SPEND_SEMANTICS: frozenset[SpendSemantics] = frozenset(
    {
        SpendSemantics.APPROVED_MEDIA_SPEND,
        SpendSemantics.NET_MEDIA_SPEND,
    }
)

GOVERNED_OVERRIDE_AUTHORITIES: frozenset[MappingAuthority] = frozenset(
    {
        MappingAuthority.USER_CONFIRMED,
        MappingAuthority.APPROVED_CUSTOM_MAPPING,
    }
)


class ScenarioType(StrEnum):
    OPTIMIZER_RECOMMENDATION = "OPTIMIZER_RECOMMENDATION"


class ScenarioStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    PROPOSED = "PROPOSED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class OptimizationProposalLifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    WITHDRAWN = "WITHDRAWN"
    STALE = "STALE"


class ProposalDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_REVISION = "REQUEST_REVISION"
    WITHDRAW = "WITHDRAW"


class ProposalReadinessStatus(StrEnum):
    PROPOSAL_READY = "PROPOSAL_READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"
    STALE = "STALE"


class ProposalReadinessCheckCode(StrEnum):
    SCENARIO_AVAILABLE = "SCENARIO_AVAILABLE"
    SOURCE_PLAN_MATCH = "SOURCE_PLAN_MATCH"
    OPTIMIZATION_RESULT_COMPLETE = "OPTIMIZATION_RESULT_COMPLETE"
    MODEL_ACCEPTED = "MODEL_ACCEPTED"
    RESULT_ARTIFACT_READBACK_VALID = "RESULT_ARTIFACT_READBACK_VALID"
    PROPOSAL_POLICY_VALID = "PROPOSAL_POLICY_VALID"
    NO_STALE_AUTHORITY = "NO_STALE_AUTHORITY"


class ProposalLimitationCode(StrEnum):
    MODEL_ESTIMATE_NOT_GUARANTEE = "MODEL_ESTIMATE_NOT_GUARANTEE"
    FIXED_BUDGET_ONLY = "FIXED_BUDGET_ONLY"
    FLEXIBLE_BUDGET_HURDLE = "FLEXIBLE_BUDGET_HURDLE"
    POSTERIOR_DEPENDENT = "POSTERIOR_DEPENDENT"
    SPEND_CONSTRAINT_APPLIED = "SPEND_CONSTRAINT_APPLIED"
    MODEL_SCOPE_LIMITED = "MODEL_SCOPE_LIMITED"
    UNMODELED_BUDGET_FIXED = "UNMODELED_BUDGET_FIXED"
    FUTURE_ASSUMPTIONS_PINNED = "FUTURE_ASSUMPTIONS_PINNED"
    EXPOSURE_RISK_FLAGS_PRESENT = "EXPOSURE_RISK_FLAGS_PRESENT"


class MaterialChangeFlag(StrEnum):
    LARGE_CHANNEL_REALLOCATION = "LARGE_CHANNEL_REALLOCATION"
    LARGE_MARKET_REALLOCATION = "LARGE_MARKET_REALLOCATION"
    ZERO_TO_NONZERO = "ZERO_TO_NONZERO"
    NONZERO_TO_ZERO = "NONZERO_TO_ZERO"


class DecisionRecordType(StrEnum):
    OPTIMIZATION_PROPOSAL = "OPTIMIZATION_PROPOSAL"


class ProposalApprovalRole(StrEnum):
    AUTHENTICATED_HUMAN_MEMBER = "authenticated_human_member"


GOVERNANCE_POLICY_VERSION = "p6-06/v1"
SCENARIO_SCHEMA_VERSION = "p6-06/v1"
MATERIAL_CHANGE_POLICY_VERSION = "p6-06/material-v1"
MATERIAL_CHANNEL_SHARE_THRESHOLD = "0.15"
MATERIAL_MARKET_SHARE_THRESHOLD = "0.10"
DEFAULT_PROPOSAL_LIMITATIONS: tuple[ProposalLimitationCode, ...] = (
    ProposalLimitationCode.MODEL_ESTIMATE_NOT_GUARANTEE,
    ProposalLimitationCode.FIXED_BUDGET_ONLY,
    ProposalLimitationCode.POSTERIOR_DEPENDENT,
    ProposalLimitationCode.SPEND_CONSTRAINT_APPLIED,
    ProposalLimitationCode.MODEL_SCOPE_LIMITED,
)
FLEXIBLE_PROPOSAL_LIMITATIONS: tuple[ProposalLimitationCode, ...] = (
    ProposalLimitationCode.MODEL_ESTIMATE_NOT_GUARANTEE,
    ProposalLimitationCode.FLEXIBLE_BUDGET_HURDLE,
    ProposalLimitationCode.POSTERIOR_DEPENDENT,
    ProposalLimitationCode.SPEND_CONSTRAINT_APPLIED,
    ProposalLimitationCode.MODEL_SCOPE_LIMITED,
    ProposalLimitationCode.FUTURE_ASSUMPTIONS_PINNED,
)
