"""Marketing Identity Graph enums. Marketing execution identity, not people."""

from __future__ import annotations

from enum import StrEnum


class MarketingIdentityNodeType(StrEnum):
    """Graph nodes. PERSONA and AUDIENCE are reserved; IG-00 does not persist them.
    Later INITIATIVE/CREATIVE/EXPERIMENT/BRAND_STUDY may extend this enum.
    """

    MARKET = "MARKET"
    CHANNEL = "CHANNEL"
    CAMPAIGN = "CAMPAIGN"
    PERSONA = "PERSONA"
    AUDIENCE = "AUDIENCE"
    PROVIDER = "PROVIDER"
    EXTERNAL_CAMPAIGN = "EXTERNAL_CAMPAIGN"
    GA4_PROPERTY = "GA4_PROPERTY"
    GA4_STREAM = "GA4_STREAM"
    BIGQUERY_GA4_SOURCE = "BIGQUERY_GA4_SOURCE"


class MarketingIdentityEdgeType(StrEnum):
    CAMPAIGN_CHILD_OF = "CAMPAIGN_CHILD_OF"
    CAMPAIGN_TARGETS_MARKET = "CAMPAIGN_TARGETS_MARKET"
    CAMPAIGN_USES_CHANNEL = "CAMPAIGN_USES_CHANNEL"
    CAMPAIGN_BOUND_TO_EXTERNAL = "CAMPAIGN_BOUND_TO_EXTERNAL"
    CAMPAIGN_TRACKED_BY = "CAMPAIGN_TRACKED_BY"
    CAMPAIGN_TARGETS_AUDIENCE = "CAMPAIGN_TARGETS_AUDIENCE"
    CAMPAIGN_TARGETS_PERSONA = "CAMPAIGN_TARGETS_PERSONA"
    AUDIENCE_REPRESENTS_PERSONA = "AUDIENCE_REPRESENTS_PERSONA"
    AUDIENCE_AVAILABLE_IN_MARKET = "AUDIENCE_AVAILABLE_IN_MARKET"
    AUDIENCE_BOUND_TO_EXTERNAL = "AUDIENCE_BOUND_TO_EXTERNAL"
    GA4_PROPERTY_COVERS_MARKET = "GA4_PROPERTY_COVERS_MARKET"
    GA4_STREAM_BELONGS_TO_PROPERTY = "GA4_STREAM_BELONGS_TO_PROPERTY"
    BIGQUERY_SOURCE_EXPORTS_PROPERTY = "BIGQUERY_SOURCE_EXPORTS_PROPERTY"


class CampaignStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETE = "COMPLETE"
    ARCHIVED = "ARCHIVED"


class TrackingKind(StrEnum):
    PREM3_UTM_ID = "PREM3_UTM_ID"
    PLATFORM_CAMPAIGN_ID = "PLATFORM_CAMPAIGN_ID"
    CUSTOM_EVENT_PARAM = "CUSTOM_EVENT_PARAM"
    MANUAL_MAPPING = "MANUAL_MAPPING"


class CampaignIdentitySource(StrEnum):
    """Deterministic authority only. FUZZY_NAME_MATCH is intentionally absent."""

    PREM3_UTM_ID = "PREM3_UTM_ID"
    EXTERNAL_CAMPAIGN_BINDING = "EXTERNAL_CAMPAIGN_BINDING"
    CUSTOM_IDENTIFIER = "CUSTOM_IDENTIFIER"
    USER_CONFIRMED_MAPPING = "USER_CONFIRMED_MAPPING"
    UNRESOLVED = "UNRESOLVED"


class BindingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONFIRMED = "CONFIRMED"
    APPROVED = "APPROVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INACTIVE = "INACTIVE"


class MappingMethod(StrEnum):
    PROVIDER_ID_EXACT = "PROVIDER_ID_EXACT"
    USER_CONFIRMED = "USER_CONFIRMED"
    CUSTOM_IDENTIFIER = "CUSTOM_IDENTIFIER"


class GA4TopologyKind(StrEnum):
    SINGLE_MASTER_PROPERTY = "SINGLE_MASTER_PROPERTY"
    PROPERTY_PER_MARKET = "PROPERTY_PER_MARKET"
    MULTI_PROPERTY_SHARED_MARKETS = "MULTI_PROPERTY_SHARED_MARKETS"
    MASTER_PLUS_REGIONAL = "MASTER_PLUS_REGIONAL"
    CUSTOM = "CUSTOM"


class SourceOverlapPolicy(StrEnum):
    DISJOINT = "DISJOINT"
    MASTER_AUTHORITATIVE = "MASTER_AUTHORITATIVE"
    REGIONAL_AUTHORITATIVE = "REGIONAL_AUTHORITATIVE"
    PARTITIONED_BY_MARKET = "PARTITIONED_BY_MARKET"
    DEDUPE_REQUIRED = "DEDUPE_REQUIRED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class MarketResolutionMethod(StrEnum):
    PROPERTY_BOUND = "PROPERTY_BOUND"
    STREAM_BOUND = "STREAM_BOUND"
    CUSTOM_DIMENSION = "CUSTOM_DIMENSION"
    HOSTNAME_MAPPING = "HOSTNAME_MAPPING"
    GEO_MAPPING = "GEO_MAPPING"
    USER_CONFIRMED_RULE = "USER_CONFIRMED_RULE"
    UNRESOLVED = "UNRESOLVED"


class ResolutionAuthority(StrEnum):
    RESOLVED = "RESOLVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNRESOLVED = "UNRESOLVED"


class IdentitySourceAuthority(StrEnum):
    USER_DECLARED = "USER_DECLARED"
    PREM3_GENERATED = "PREM3_GENERATED"
    PROVIDER_DISCOVERED = "PROVIDER_DISCOVERED"
    DATA_FOUNDATION_DISCOVERED = "DATA_FOUNDATION_DISCOVERED"
    USER_CONFIRMED = "USER_CONFIRMED"
    SYSTEM_VERIFIED = "SYSTEM_VERIFIED"


class IdentityGraphCapabilityState(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    PARTIAL = "PARTIAL"
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class IdentityGraphComponentState(StrEnum):
    CAMPAIGN_LEDGER_READY = "CAMPAIGN_LEDGER_READY"
    GA4_TOPOLOGY_READY = "GA4_TOPOLOGY_READY"


class TrackingImplementationStatus(StrEnum):
    GENERATED = "GENERATED"
    COPIED = "COPIED"
    VALIDATED = "VALIDATED"
    MAPPED = "MAPPED"


class TopologyStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    PARTIAL = "PARTIAL"
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
