"""Data Foundation enums. Distinct from MODEL_READY and M2-11 IMPORT_READY."""

from __future__ import annotations

from enum import StrEnum


class EvidenceRequirementType(StrEnum):
    KPI = "KPI"
    MEDIA = "MEDIA"
    PROMOTION = "PROMOTION"
    PRICING = "PRICING"
    INVENTORY = "INVENTORY"
    DISTRIBUTION = "DISTRIBUTION"
    SALES_ACTIVITY = "SALES_ACTIVITY"
    COMPETITION = "COMPETITION"
    EXTERNAL_CONTROL = "EXTERNAL_CONTROL"
    EXPERIMENT_EVIDENCE = "EXPERIMENT_EVIDENCE"
    PRIOR_MMM = "PRIOR_MMM"
    OTHER_CUSTOM = "OTHER_CUSTOM"


class CoverageState(StrEnum):
    SOURCE_FOUND = "SOURCE_FOUND"
    SOURCE_PARTIAL = "SOURCE_PARTIAL"
    SOURCE_NOT_CONNECTED = "SOURCE_NOT_CONNECTED"
    SOURCE_NOT_COLLECTED = "SOURCE_NOT_COLLECTED"
    PREM3_PROVIDED = "PREM3_PROVIDED"


class CoverageBucketState(StrEnum):
    VERIFIED_PRESENT = "VERIFIED_PRESENT"
    VALID_ZERO = "VALID_ZERO"
    PARTIAL = "PARTIAL"
    EXPECTED_BUT_MISSING = "EXPECTED_BUT_MISSING"
    UNKNOWN = "UNKNOWN"
    NOT_EXPECTED = "NOT_EXPECTED"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    PREM3_PROVIDED = "PREM3_PROVIDED"
    OUTSIDE_TARGET_WINDOW = "OUTSIDE_TARGET_WINDOW"
    OVERLAP_UNDER_RECONCILIATION = "OVERLAP_UNDER_RECONCILIATION"


class CoverageView(StrEnum):
    REQUIRED_EVIDENCE = "REQUIRED_EVIDENCE"
    ALL_SOURCES = "ALL_SOURCES"


class CoverageGapCategory(StrEnum):
    COVERAGE_GAP = "COVERAGE_GAP"
    SOURCE_FAILURE = "SOURCE_FAILURE"
    BUSINESS_PAUSE = "BUSINESS_PAUSE"
    PROVIDER_TRANSITION = "PROVIDER_TRANSITION"
    PARTIAL_PERIOD = "PARTIAL_PERIOD"
    LATE_ARRIVAL = "LATE_ARRIVAL"
    UNKNOWN = "UNKNOWN"


class CycleCadence(StrEnum):
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    SEMIANNUAL = "SEMIANNUAL"
    ANNUAL = "ANNUAL"
    EVENT_BASED = "EVENT_BASED"
    ONE_TIME = "ONE_TIME"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"


class TargetWindowStatus(StrEnum):
    PROVISIONAL = "PROVISIONAL"
    CONFIRMED_DOWNSTREAM = "CONFIRMED_DOWNSTREAM"


class CutoffOrigin(StrEnum):
    DETECTED = "DETECTED"
    USER_SELECTED = "USER_SELECTED"


class PreviewMode(StrEnum):
    SOURCE_PREVIEW = "SOURCE_PREVIEW"
    TRANSFORMATION_PREVIEW = "TRANSFORMATION_PREVIEW"
    CANONICAL_PREVIEW = "CANONICAL_PREVIEW"


class RowCountKind(StrEnum):
    EXACT = "EXACT"
    ESTIMATED = "ESTIMATED"
    SAMPLED = "SAMPLED"
    UNKNOWN = "UNKNOWN"


class ScopeProvenance(StrEnum):
    SCHEMA_DETECTED = "SCHEMA_DETECTED"
    PROFILE_DETECTED = "PROFILE_DETECTED"
    PROVIDER_METADATA = "PROVIDER_METADATA"
    FILENAME_INFERRED = "FILENAME_INFERRED"
    USER_PROVIDED = "USER_PROVIDED"
    BUSINESS_IQ_INFERRED = "BUSINESS_IQ_INFERRED"
    UNKNOWN = "UNKNOWN"


class ConfirmationClass(StrEnum):
    CONFIRMED = "CONFIRMED"
    LIKELY = "LIKELY"
    NEEDS = "NEEDS"
    NONE = "NONE"


class LocationType(StrEnum):
    BIGQUERY = "BIGQUERY"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    PLATFORM_ONLY = "PLATFORM_ONLY"
    UNAVAILABLE = "UNAVAILABLE"


class ProvenanceClass(StrEnum):
    VERIFIED = "VERIFIED"
    DETECTED = "DETECTED"
    INFERRED = "INFERRED"
    USER_PROVIDED = "USER_PROVIDED"
    PROVIDER_DOCUMENTED = "PROVIDER_DOCUMENTED"
    UNKNOWN = "UNKNOWN"


class ConnectionLifecycle(StrEnum):
    NOT_CONNECTED = "NOT_CONNECTED"
    AUTHORIZATION_PENDING = "AUTHORIZATION_PENDING"
    AUTHORIZED = "AUTHORIZED"
    DISCOVERY_READY = "DISCOVERY_READY"
    PROVISIONING_READY = "PROVISIONING_READY"
    ACCESS_REVOKED = "ACCESS_REVOKED"
    ERROR = "ERROR"


class QualityStatus(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    BLOCKER = "BLOCKER"
    UNKNOWN = "UNKNOWN"
    SKIPPED_NOT_APPLICABLE = "SKIPPED_NOT_APPLICABLE"


class QualityFamily(StrEnum):
    UNIQUENESS = "UNIQUENESS"
    COMPLETENESS = "COMPLETENESS"
    TYPE_PARSE = "TYPE_PARSE"
    FORMATTING = "FORMATTING"
    DOMAIN = "DOMAIN"
    TEMPORAL = "TEMPORAL"
    REFERENTIAL = "REFERENTIAL"
    RECONCILIATION = "RECONCILIATION"
    DRIFT = "DRIFT"


class ConsequenceClass(StrEnum):
    FOUNDATION_BLOCKER = "FOUNDATION_BLOCKER"
    SOURCE_BLOCKER = "SOURCE_BLOCKER"
    PREMODEL_BLOCKER = "PREMODEL_BLOCKER"
    PREMODEL_REVIEW = "PREMODEL_REVIEW"
    ADVISORY = "ADVISORY"


class TransformAuthority(StrEnum):
    AUTO_SAFE = "AUTO_SAFE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    USER_REQUIRED = "USER_REQUIRED"
    NOT_RECOMMENDED = "NOT_RECOMMENDED"


class TransformId(StrEnum):
    DF_T001 = "DF-T001"
    DF_T002 = "DF-T002"
    DF_T003 = "DF-T003"
    DF_T004 = "DF-T004"
    DF_T005 = "DF-T005"
    DF_T006 = "DF-T006"
    DF_T007 = "DF-T007"
    DF_T008 = "DF-T008"
    DF_T009 = "DF-T009"
    DF_T010 = "DF-T010"
    DF_T011 = "DF-T011"
    DF_T012 = "DF-T012"
    DF_T013 = "DF-T013"
    DF_T014 = "DF-T014"
    DF_T015 = "DF-T015"
    DF_T016 = "DF-T016"
    DF_T017 = "DF-T017"
    DF_T018 = "DF-T018"
    DF_T019 = "DF-T019"
    DF_T020 = "DF-T020"
    DF_T021 = "DF-T021"
    DF_T022 = "DF-T022"


class PlanActionKind(StrEnum):
    REUSE = "REUSE"
    CREATE = "CREATE"
    CHANGE = "CHANGE"
    CUSTOMER_MANAGED = "CUSTOMER_MANAGED"


class FoundationPlanSection(StrEnum):
    INFRASTRUCTURE = "INFRASTRUCTURE"
    SOURCES_AND_TRANSFERS = "SOURCES_AND_TRANSFERS"
    QUALITY_AND_TRANSFORMATIONS = "QUALITY_AND_TRANSFORMATIONS"
    CANONICAL_ASSETS = "CANONICAL_ASSETS"
    GOVERNANCE_AND_OBSERVABILITY = "GOVERNANCE_AND_OBSERVABILITY"


class SourceFoundationStatus(StrEnum):
    """DF source-level readiness. Never emits M2-11 IMPORT_READY."""

    FOUNDATION_SOURCE_NOT_READY = "FOUNDATION_SOURCE_NOT_READY"
    FOUNDATION_SOURCE_READY = "FOUNDATION_SOURCE_READY"


class DataFoundationReadyStatus(StrEnum):
    NOT_READY = "NOT_READY"
    DATA_FOUNDATION_READY = "DATA_FOUNDATION_READY"


class AlignmentVerdict(StrEnum):
    COMPATIBLE = "COMPATIBLE"
    NORMALIZE = "NORMALIZE"
    REVIEW_NEEDED = "REVIEW_NEEDED"
    RESOLVED = "RESOLVED"
    INCOMPATIBLE = "INCOMPATIBLE"


class CandidateGroup(StrEnum):
    VERIFIED = "VERIFIED"
    LIKELY = "LIKELY"
    NEEDS_DECISION = "NEEDS_DECISION"
    EXCLUDED = "EXCLUDED"


class ExecutionStatus(StrEnum):
    PREVIEWED = "PREVIEWED"
    APPROVED = "APPROVED"
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class PeriodStatus(StrEnum):
    OBSERVED = "OBSERVED"
    UNKNOWN_MISSING = "UNKNOWN_MISSING"
    ZERO_PROVEN = "ZERO_PROVEN"


class ProviderProvisionerState(StrEnum):
    PLATFORM_ONLY = "PLATFORM_ONLY"
    PREREQUISITE_REQUIRED = "PREREQUISITE_REQUIRED"
    PROVISIONING_ELIGIBLE = "PROVISIONING_ELIGIBLE"
    PLAN_READY = "PLAN_READY"
    APPROVED = "APPROVED"
    PROVISIONING = "PROVISIONING"
    FIRST_SYNC = "FIRST_SYNC"
    QA_REVIEW = "QA_REVIEW"
    PROVIDER_SYNC_COMPLETE = "PROVIDER_SYNC_COMPLETE"
