"""Business IQ enums. Distinct from Data Foundation and M2-11 readiness."""

from __future__ import annotations

from enum import StrEnum


class KnowledgeState(StrEnum):
    UNKNOWN = "UNKNOWN"
    USER_REPORTED = "USER_REPORTED"
    EXTRACTED = "EXTRACTED"
    SYSTEM_OBSERVED = "SYSTEM_OBSERVED"
    INFERRED = "INFERRED"
    CONFLICTING = "CONFLICTING"
    STALE = "STALE"
    UNKNOWN_ACKNOWLEDGED = "UNKNOWN_ACKNOWLEDGED"


class ConfirmationState(StrEnum):
    UNCONFIRMED = "UNCONFIRMED"
    USER_CONFIRMED = "USER_CONFIRMED"
    MODELER_CONFIRMED = "MODELER_CONFIRMED"
    REJECTED = "REJECTED"


class FactSourceType(StrEnum):
    USER = "USER"
    DOCUMENT = "DOCUMENT"
    REGISTRY = "REGISTRY"
    SYSTEM = "SYSTEM"
    DATA_DERIVED = "DATA_DERIVED"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    EXTERNAL_EVIDENCE = "EXTERNAL_EVIDENCE"
    INFERRED = "INFERRED"


class FactProvenance(StrEnum):
    PROVIDED_BY_USER = "PROVIDED_BY_USER"
    FROM_USER_DESCRIPTION = "FROM_USER_DESCRIPTION"
    DETECTED_IN_DATA = "DETECTED_IN_DATA"
    CONFIRMED_BY_USER = "CONFIRMED_BY_USER"
    INFERRED_NEEDS_CONFIRMATION = "INFERRED_NEEDS_CONFIRMATION"
    UNKNOWN_ACKNOWLEDGED = "UNKNOWN_ACKNOWLEDGED"


class ChannelLifecycle(StrEnum):
    DECLARED = "DECLARED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    RETIRED = "RETIRED"


class EventType(StrEnum):
    PROMOTION = "PROMOTION"
    PRICE_CHANGE = "PRICE_CHANGE"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    PRODUCT_DISCONTINUATION = "PRODUCT_DISCONTINUATION"
    MARKET_ENTRY = "MARKET_ENTRY"
    MARKET_EXIT = "MARKET_EXIT"
    MEDIA_LAUNCH = "MEDIA_LAUNCH"
    MEDIA_PAUSE = "MEDIA_PAUSE"
    BUDGET_POLICY_CHANGE = "BUDGET_POLICY_CHANGE"
    CAMPAIGN_STRATEGY_CHANGE = "CAMPAIGN_STRATEGY_CHANGE"
    BRAND_REFRESH = "BRAND_REFRESH"
    TRACKING_CHANGE = "TRACKING_CHANGE"
    DISTRIBUTION_CHANGE = "DISTRIBUTION_CHANGE"
    STORE_OPENING = "STORE_OPENING"
    STORE_CLOSURE = "STORE_CLOSURE"
    INVENTORY_CONSTRAINT = "INVENTORY_CONSTRAINT"
    CAPACITY_CONSTRAINT = "CAPACITY_CONSTRAINT"
    COMPETITOR_EVENT = "COMPETITOR_EVENT"
    REGULATORY_EVENT = "REGULATORY_EVENT"
    MACRO_EVENT = "MACRO_EVENT"
    OTHER = "OTHER"
    CUSTOM = "CUSTOM"


class HypothesisStatus(StrEnum):
    OPEN = "OPEN"
    SUPPORTED = "SUPPORTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ProposalDecision(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ClarificationAnswer(StrEnum):
    CONFIRMED_BUSINESS_PAUSE = "CONFIRMED_BUSINESS_PAUSE"
    NOT_PAUSED = "NOT_PAUSED"
    UNKNOWN = "UNKNOWN"


class BusinessContextReadyStatus(StrEnum):
    NOT_READY = "NOT_READY"
    BUSINESS_CONTEXT_READY = "BUSINESS_CONTEXT_READY"
